#!/usr/bin/env bash
# The full-Mathlib gate: build the generator and the pinned patched lean4export,
# export a pinned Mathlib, and run that export through the generator in one pass.
#
# What the gate proves, over the whole corpus rather than over fixtures:
#   * every inductive is modelled -- nothing declines;
#   * Lean's kernel accepts each generated island as it is produced
#     (`--type-check-generated`, on by default and stated here);
#   * every generated model family passes the structural output check;
#   * every generated statement matches its exact exported owner interface, and
#     universe planning never escapes.
# `scripts/check-mathlib-result.sh` reads the log and enforces all of that.
#
# What the gate deliberately does not prove:
#   * the pinned Mathlib export's own kernel validity. `--no-type-check-input`:
#     the input is an assumption of this gate, not a claim of it.
#     `test/scripts/check_arena_corpus.py` still exercises `--type-check-input`
#     over a real corpus, the published Lean Kernel Arena cases.
#   * serialization round-tripping. `--no-output` writes no artifact, so nothing
#     here re-reads generated bytes. That is covered by axis 4 of `lake exe
#     test`'s fixture sweep -- `parse (render (parse t)) = parse t` -- and by
#     `lake exe mainclitest`, which writes exports to real paths and reads them
#     back. `check_arena_corpus.py` runs `--no-output` and does not cover it.
# The gate used to write a 5.9 GB artifact and re-read it under
# `--type-check-input`, which was the only kernel check in the run -- generated
# islands were checked `0` times. Moving the kernel to island time trades a
# duplicate of the fixture suites' round-trip coverage for kernel coverage of
# the generated declarations, which nothing else has at this scale.
#
# Nothing here measures memory. Generation's peak RSS is a design criterion, not
# a CI verdict: lean4checker parses and kernel-checks this same corpus in about
# 9 GB, and a tool that does that *and* generates models should stay near that
# number -- drifting well past it is evidence about the design, whatever a
# runner survives. That is a question a developer asks deliberately, so measure
# it deliberately: run the generation pipeline below under `/usr/bin/time -v`.
# docs/maintainers/Testing.md records the target and the current baseline.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WORK="$ROOT/_tmp"
MATHLIB_DIR="$WORK/mathlib"
EXPORTER_DIR="$WORK/lean4export"
EXPORT_GZ="$WORK/mathlib.ndjson.gz"
LOG="$WORK/logs/generate.log"

MATHLIB_REV="5e932f97dd25535344f80f9dd8da3aab83df0fe6"
EXPORTER_REV="caccfbebbc99077962b3321125b2375bb3fa22db"
EXPORTER_PATCH="$ROOT/vendor/lean4export/compact-expr-interner.patch"
EXPORTER_PATCH_SHA="151c25f6adbfd915ce62786da33352c089653f62d5d3445cc3b38879de19deeb"
# Lake's build parallelism bound. Lake 5.0.0 has no job-count flag, so this is
# `LEAN_NUM_THREADS`; test/scripts/check-ci-serialized-builds.sh pins it equal to
# the value ci.yml states for the fast jobs.
BUILD_THREADS=4

cd "$ROOT"
mkdir -p "$WORK/logs" "$WORK/tmp"
export TMPDIR="$WORK/tmp"

checkout_pinned() {
  local url="$1" revision="$2" directory="$3"
  rm -rf -- "$directory"
  git clone --filter=blob:none --no-checkout "$url" "$directory"
  git -C "$directory" fetch --depth=1 origin "$revision"
  git -C "$directory" checkout --detach FETCH_HEAD
}

LEAN_NUM_THREADS="$BUILD_THREADS" lake build lean-inductive-models

checkout_pinned https://github.com/leanprover/lean4export.git "$EXPORTER_REV" "$EXPORTER_DIR"
echo "$EXPORTER_PATCH_SHA  $EXPORTER_PATCH" | sha256sum --check --strict
git -C "$EXPORTER_DIR" apply --check "$EXPORTER_PATCH"
git -C "$EXPORTER_DIR" apply "$EXPORTER_PATCH"
# Deliberately a literal, not a copy of `$ROOT/lean-toolchain`: the NDJSON export
# is the interface between the two, and the exporter has to load Mathlib's oleans
# under the version that built them. `scripts/export-fixture.sh` pins the same.
echo "leanprover/lean4:v4.29.1" > "$EXPORTER_DIR/lean-toolchain"
(cd "$EXPORTER_DIR" && LEAN_NUM_THREADS="$BUILD_THREADS" lake build)

checkout_pinned https://github.com/leanprover-community/mathlib4.git "$MATHLIB_REV" "$MATHLIB_DIR"
(cd "$MATHLIB_DIR" && lake exe cache get)

# Export to a compressed file rather than piping the exporter straight into the
# generator: serializing the two is what fits them on a 16 GiB runner, and gzip
# keeps the 5.6 GB uncompressed export off the disk as well. Only the exporter
# may write to this pipeline's stdout -- a stray diagnostic there is compressed
# into the export itself and surfaces much later as a parse error.
if ! (cd "$MATHLIB_DIR" && lake env "$EXPORTER_DIR/.lake/build/bin/lean4export" Mathlib) |
    gzip -1 > "$EXPORT_GZ"; then
  echo "mathlib gate: export failed, (exporter gzip) = (${PIPESTATUS[*]})" >&2
  exit 1
fi
# The exporter writes nothing to the job log, so this line is the only mark
# between the cache phase and generation, and the only report of the export's
# size. Both are worth one line when reading a 7,000-line log after the fact.
echo "compressed Mathlib export bytes: $(stat -c '%s' "$EXPORT_GZ")"
rm -rf -- "$MATHLIB_DIR"

# One pass, reading the exact exported byte stream from stdin so the
# uncompressed export never lands on disk, and writing no output at all.
if ! gzip -dc "$EXPORT_GZ" |
    LEAN_INDUCTIVE_MODELS_OUTPUT_BACKEND_TRACE=1 \
      "$ROOT/.lake/build/bin/lean-inductive-models" - \
      --no-output --no-type-check-input --type-check-generated 2>&1 |
    tee "$LOG"; then
  echo "mathlib gate: generation failed, (gzip generator tee) = (${PIPESTATUS[*]})" >&2
  exit 1
fi

"$ROOT/scripts/check-mathlib-result.sh" "$LOG"
