import InductiveModels.Driver.Serialise
import InductiveModels.Driver.Readiness

/-!
# The one entry, and the rungs under it

[`modelBlock`] is the one way an inductive block gets a model. The stream
hands it every input block after replay; a model hands it every block it
introduced — the tag and auxiliary a mutual model composes into, the members a
nested model specialises into, the skeletons and pairs a simple model splices —
and those go through the same head: the basis is exempt, the consumer's
[`NativeSupport`] is asked, and only then is a construction chosen by the shape
of the block alone. Under it, [`genNested`], [`genMutual`] and [`genPrim`] are
the three constructions, and each one closes its own introductions by calling
back up into the entry.

This is where the three constructions meet; nothing above it knows there is
more than one.
-/

open Lean Meta

namespace InductiveModels

private abbrev ModelIslandState (α : Type) :=
  Array EDecl × Report × Array PendingModel × Array α


/-- An exact public name generated by an earlier composed step is not part of
the input's `reserved` set.  Check those spellings before a collision-safe
retry so aliasing can never weaken `nameTaken`. -/
def exactPrimNameTaken? (tname : Name) (ctors : Array (Name × Expr))
    (_projections : Array EProjection) : MetaM (Option Name) := do
  let env ← getEnv
  let recursor := Name.str tname "rec"
  for n in #[Naming.modelName tname, Naming.modelName recursor] do
    if env.constants.contains n then return some n
  for (ctor, _) in ctors do
    let n := Naming.modelName ctor
    if env.constants.contains n then return some n
  for j in [0:ctors.size] do
    let n := Naming.iotaName recursor j
    if env.constants.contains n then return some n
  if let some (.recInfo info) := env.constants.find? recursor then
    if info.k then
      let n := Naming.ruleKName recursor
      if env.constants.contains n then return some n
  if let some (.inductInfo info) := env.constants.find? tname then
    -- The block as export records, so the eta name is predicted by the very
    -- predicate that emits it — including its reading of recursion, which is
    -- what survives reduction and not `info.isRec`.
    let .induct blockTypes blockCtors _ ← indEDecl info.all.toArray | return none
    let some type := blockTypes.find? (·.name == tname) | return none
    if type.isKernelStructureLike blockCtors (.ofEnvironment env) &&
        !(← isPropFormerType info.type) then
      let n := Naming.etaName tname
      if env.constants.contains n then return some n
    if ctors.size == 1 then
      let ctorName := ctors[0]!.1
      let some constructor := blockCtors.find? fun constructor =>
          constructor.name == ctorName && constructor.induct == tname
        | return none
      for fieldIndex in ← eligibleProjectionFieldsM type constructor do
        for n in #[Naming.projectionName tname fieldIndex,
            Naming.projectionIotaName tname fieldIndex] do
          if env.constants.contains n then return some n
  return none

/-- Where a block reached the entry from. The construction chosen never
depends on this ([`modelBlock`] reads the block alone); two things do, and
both are about the CLI rather than about shapes. `--simple` and `--basic`
select by provenance: an input's ordinary inductives against its bootstrap
ones and everything a model introduced to reach the basis. And a bound model
name means two different things: for an input block it is a collision to
report, for a spliced one it is this run's own earlier model of the same
support, and modelling it again would bind the same names twice. -/
inductive BlockOrigin where
  /-- A block of the input export. -/
  | input
  /-- A block a mutual or nested model composes into: the implementation tag
  and auxiliary, or the specialised members. -/
  | composed
  /-- A block a model spliced to write itself in: a skeleton, a pair, a core. -/
  | spliced
  deriving Repr, BEq

/-- What the driver hands the entry: the route gates the command line set,
and what the consumer of the output handles itself. -/
structure Routing where
  generation : Cli.Config
  native : NativeSupport := NativeSupport.none

/-- A block's construction inputs as the environment holds them. The exact
export record decides syntax and the environment decides construction, and the
two are kept apart on purpose: a test seam may perturb the exact records a
composed consumer sees, and that must reach the statement comparison rather
than be built from. -/
private def installedBlock (all : Array Name) :
    MetaM (Array Expr × Array (Array (Name × Expr))) :=
  blockOf all

mutual

/-- **The one entry every inductive block passes through.** Basis members are
left as they are without a word: they are what every construction is written
in, and the input's own basis records are validated and reported by the stream
before they get here. A block the consumer's [`NativeSupport`] accepts is
reported on the `native` row and left as it is. What remains is routed by
shape: nesting to [`genNested`], several members to [`genMutual`], one member
to [`genPrim`]; each route is behind its command-line gate, and a gate that is
off leaves the block untouched and unreported, as it always has. -/
partial def modelBlock (block : EDecl) (origin : BlockOrigin) (routing : Routing)
    (reserved : Std.HashSet Name) (normalizer : ExactNormalizationEnv)
    (st : ModelIslandState α) (exactTransform : EDecl → EDecl := id)
    (observer? : Option (IslandObserver α) := none) : MetaM (ModelIslandState α) := do
  let .induct ts cs recs := block | return st
  let t :: _ := ts | return st
  let all := ts.toArray.map (·.name)
  let generation := routing.generation
  if all.any inductiveBasis.contains then return st
  if routing.native block then
    let (out, rep, pending, observations) := st
    return (out, { rep with native := rep.native.push t.name }, pending, observations)
  if origin matches .spliced then
    -- Already modelled: the declaration-local carrier itself is the key.
    if (← getEnv).constants.contains (Naming.modelName t.name) then return st
  if ts.any (·.numNested > 0) then
    unless generation.nested do return st
    genNested block ts cs recs routing reserved st exactTransform observer?
  else if ts.length > 1 then
    unless generation.mutualModels do return st
    let (tys, ctors) ← installedBlock all
    genMutual all t.levelParams t.numParams tys ctors #[] reserved routing st
      (some block) (presentation := origin matches .input) exactTransform observer?
  else
    let selected := match origin with
      | .spliced => generation.basic
      | .input | .composed => generation.modelsSimpleInput t.name
    unless selected do return st
    let (tys, ctors) ← installedBlock all
    genPrim t.name t.levelParams t.numParams tys[0]! ctors[0]! #[] reserved routing st
      (some (block, normalizer)) exactTransform observer?

/-- The blocks a model introduced, each through the entry once. `members` is
how a model names what it introduced — every member of a composed block,
everything spliced — and several members may share one block, which is asked
once. A spliced name that is not an inductive type (`Eq.refl`, `funext`,
`Nat.rec`) has no block to ask about; a basis member is not looked up at all,
since it has no generated block snapshot and the entry would say nothing
about it anyway. -/
partial def modelMembers (members : Array Name) (blocks : ExactGeneratedBlocks)
    (origin : BlockOrigin) (routing : Routing) (reserved : Std.HashSet Name)
    (st : ModelIslandState α) (exactTransform : EDecl → EDecl := id)
    (observer? : Option (IslandObserver α) := none) : MetaM (ModelIslandState α) := do
  let mut st := st
  let mut asked : Std.HashSet Name := {}
  for n in members do
    if inductiveBasis.contains n then continue
    let some (.inductInfo _) := (← getEnv).constants.find? n | continue
    let block ← blocks.require n
    let .induct (root :: _) _ _ := block | continue
    if asked.contains root.name then continue
    asked := asked.insert root.name
    -- Generated projection-iota closing uses only `ExactNormalizationEnv.beta`;
    -- that operation deliberately consults no named definition, so a
    -- one-block normalizer cannot lose persistent/source aliases.
    let normalizer := ({ metaLine := .null, decls := #[block] } : Export).exactNormalizationEnv
    st ← modelBlock block origin routing reserved normalizer st exactTransform observer?
  return st

/-- One nested declaration's model, generated and accounted for —
[`InductiveModels.iso`] over the plan [`InductiveModels.plan`] drew. The
model specialises the declaration into a mutual block and proves the export's
recursors over it; that block is then a block like any other and goes back
through the entry, which is where the mutual construction and, under it, the
simple one take over.

The model must not mention the declaration it models — every island is
emitted before its owner and kernel-checked in an owner-free environment — and
it is written not to; the owner-free check at island close is what enforces it. -/
partial def genNested (block : EDecl) (ts : List EIndType) (cs : List ECtor) (recs : List ERec)
    (routing : Routing) (reserved : Std.HashSet Name) (st : ModelIslandState α)
    (exactTransform : EDecl → EDecl := id)
    (observer? : Option (IslandObserver α) := none) : MetaM (ModelIslandState α) := do
  let (out, rep, pending, observations) := st
  let t :: _ := ts | return st
  let all := ts.toArray.map (·.name)
  let (tys, ctors) ← installedBlock all
  let ptypes : Array PType := (Array.range all.size).map fun i =>
    { name := all[i]!, type := tys[i]!, ctors := ctors[i]! }
  match plan (← getEnv) t.levelParams t.numParams ptypes with
  | .error e => return (out, { rep with declined := rep.declined.push (t.name, e) },
      pending, observations)
  | .ok none => return st
  | .ok (some pl) =>
    let saved ← getEnv
    let inputRecursors := recs.toArray
    let generate := fun (buildRoot? : Option Name) => do
      let is ← iso all t.levelParams t.numParams ctors inputRecursors pl reserved buildRoot?
      addStructureModels ts.toArray cs.toArray inputRecursors #[] reserved is
    let mut result ← (generate none).run
    if let .error (.nameLost _) := result then
      setEnv saved
      result ← (generate (some (Naming.retryRoot t.name))).run
    match result with
    | .error dec =>
      setEnv saved
      return (out, rep.withDecline t.name dec "nested", pending, observations)
    | .ok is =>
      let serialised ← serialiseIso block is exactTransform observer?
      let records := serialised.records
      let is := serialised.model
      let out := appendModelRecords out records t.name
      let mut rep := { rep with generated := rep.generated.push (t.name, is.decls.size) }
      unless is.spliced.isEmpty do
        rep := { rep with spliced := rep.spliced.push (t.name, is.spliced) }
      let observations := serialised.observation?.elim observations observations.push
      let pending := pending.push { spliced := is.spliced }
      -- The model of the specialised block remains in this same atomic owner
      -- transition.
      modelMembers is.members serialised.exactBlocks .composed routing reserved
        (out, rep, pending, observations) exactTransform observer?

/-- One simple inductive's model from the primitives, generated and
accounted for — [`InductiveModels.primIso`], selected by `--simple` for an
input block and `--basic` for a spliced one. Shared by the input's own simple
inductives and everything the other two constructions compose into.

**And models for whatever that model had to splice**, through the entry.
A spliced inductive enters the private forest as part of its consumer's
model, so a model's own introductions are the next blocks to ask about; the
basis is the exemption that makes this well-founded, and a spliced block the
entry has already modelled is asked no second time. Its model is placed
immediately before that exact owner record while retaining the parent's
earlier dependency prefix. -/
partial def genPrim (tname : Name) (lparams : List Name) (np : Nat) (ty : Expr)
    (ctors : Array (Name × Expr))
    (projections : Array EProjection)
    (reserved : Std.HashSet Name) (routing : Routing)
    (st : ModelIslandState α) (sourceBlock? : Option (EDecl × ExactNormalizationEnv) := none)
    (exactTransform : EDecl → EDecl := id)
    (observer? : Option (IslandObserver α) := none) :
    MetaM (ModelIslandState α) := do
  let (out, rep, pending, observations) := st
  let saved ← getEnv
  -- **The retry under an alias root**, and it is a retry rather than a
  -- decision taken up front on purpose: aliasing changes nothing about the
  -- output and everything about the risk, so it runs only where the collision
  -- has actually fired. Every declaration that models today takes exactly the
  -- path it took before, byte for byte.
  --
  -- The alias embeds the exact original below a public namespace.  This is
  -- injective even for distinct raw private names that normalize to the same
  -- user name, because `_private` is no longer the leading component.
  let aliasRoot : Name := Naming.retryRoot tname
  let mut root := tname
  let sourceRecursor? := sourceBlock?.bind fun (block, _) => match block with
    | .induct _ _ recursors => recursors.find? (·.name == Name.str tname "rec")
    | _ => none
  let sourceType? := sourceBlock?.bind fun (block, _) => match block with
    | .induct types _ _ => types.find? (·.name == tname)
    | _ => none
  let sourceConstructor? := sourceBlock?.bind fun (block, _) => match block with
    | .induct _ constructors _ => constructors.find? (·.induct == tname)
    | _ => none
  let attachStructureModels := fun (is : Iso) => match sourceBlock? with
    | some (block, normalizer) =>
      addSourceStructureModels block projections normalizer reserved is
    | none => addInstalledStructureModels #[tname] projections reserved is
  -- **Route selection is a property of the declaration, not of its
  -- provenance.** The predicate below reads only the block being modelled —
  -- its exact serialized type, constructor and recursor — so an inductive a
  -- model spliced (the carve arm's index erasure, the composition's tag and
  -- auxiliary) is asked exactly the question an input inductive is asked.
  -- Gating the question on "did this come from the input stream?" made a
  -- generated owner miss the one-layer implementation certificate that its own
  -- source owner carries, and with it the literal projection-iota contract
  -- ([`InductiveModels.addProjectionModels`]); the erasure skeleton of an
  -- indexed fibre owner was the observable case.
  --
  -- **An unindexed owner has no adapter at all.** It is the simple
  -- construction's own, whatever its constructor count: the public carrier,
  -- constructor, recursor, ι rules and intrinsic projections all come out of
  -- [`InductiveModels.primIso`] at the exact source syntax, so a private
  -- fixpoint with a rolled public layer over it bought nothing a route had to
  -- exist for and cost one `Eq.rec` transport per recursive field.
  let selectIndexedFibre ←
      match sourceType?, sourceConstructor?, sourceRecursor? with
      | some sourceType, some sourceConstructor, some sourceRecursor =>
        phase1IndexedFibreOneLayerEligible tname np ty ctors sourceType
          sourceConstructor sourceRecursor
      | _, _, _ => pure false
  let exactTaken ← exactPrimNameTaken? tname ctors projections
  let initial ← match exactTaken with
    | some n => pure (.error (.nameTaken n))
    | none => (do
        let is ← if selectIndexedFibre then
            let some sourceRecursor := sourceRecursor?
              | badShape s!"{tname}'s selected indexed fibre has no exact recursor"
            let some sourceConstructor := ctors[0]?
              | badShape s!"{tname}'s selected indexed fibre has no constructor"
            indexedFibreOneLayerIso tname root lparams np ty sourceConstructor sourceRecursor reserved
          else
            primIso tname root lparams np ty ctors reserved
              (sourceRecursor? := sourceRecursor?)
        attachStructureModels is).run
  let mut res := initial
  if let .error (.nameLost _) := res then
    setEnv saved
    root := aliasRoot
    res ← (do
      let is ← if selectIndexedFibre then
          let some sourceRecursor := sourceRecursor?
            | badShape s!"{tname}'s selected indexed fibre has no exact recursor"
          let some sourceConstructor := ctors[0]?
            | badShape s!"{tname}'s selected indexed fibre has no constructor"
          indexedFibreOneLayerIso tname root lparams np ty sourceConstructor sourceRecursor reserved
        else
          primIso tname root lparams np ty ctors reserved
            (sourceRecursor? := sourceRecursor?)
      attachStructureModels is).run
  match res with
  | .error dec =>
    setEnv saved
    -- **Exempt is not declined.** A basis primitive is what the construction
    -- is written in, so its absence from the models is the thing that makes
    -- the construction well-founded rather than a shape it cannot reach; it
    -- gets its own row and is out of the decline count.
    if dec matches .basisExempt then
      return (out, { rep with exempt := rep.exempt.push (tname, dec.labelAs "prim") },
        pending, observations)
    return (out, rep.withDecline tname dec "prim",
      pending, observations)
  | .ok is =>
    let source ← match sourceBlock? with
      | some (block, _) => pure block
      | none => indEDecl #[tname]
    let serialised ← serialiseIso source is exactTransform observer?
    let records := serialised.records
    let is := serialised.model
    let out := appendModelRecords out records tname
    let mut rep := { rep with generated := rep.generated.push (tname, is.decls.size) }
    unless is.spliced.isEmpty do
      rep := { rep with spliced := rep.spliced.push (tname, is.spliced) }
    let observations := serialised.observation?.elim observations observations.push
    let st2 := (out, rep, pending.push { spliced := is.spliced }, observations)
    let st2 ← modelMembers is.spliced serialised.exactBlocks .spliced routing reserved st2
      exactTransform observer?
    -- **A model may not leave an inductive it introduced unmodelled.** The carve arm
    -- splices the index erasure of the family it is
    -- carving, so its output contains an inductive that was in nobody's
    -- input; if the descent above could not model it, emitting would put a
    -- additional unmodelled inductive in front of a consumer, which splice
    -- closure prevents. An inductive the consumer handles natively is closed
    -- as it stands.
    -- So the whole model is withdrawn and the declaration declines.
    --
    -- Checked **after** the descent and not predicted before it. A cheap test
    -- that says "this skeleton will model" is the shape of "skip is not
    -- pass": it reports success and leaves the hole open on the case it got
    -- wrong. This asks the environment.
    if routing.generation.basic then
      for n in is.requires do
        let closed ← do
          if (← getEnv).constants.contains (Naming.modelName n) then pure true
          else if inductiveBasis.contains n then pure true
          else pure (routing.native (← serialised.exactBlocks.require n))
        unless closed do
          -- **Withdraw everything**, and off `st` rather than off the locals:
          -- `out`, `rep` and `pending` have all been added to by the emission
          -- and the descent above, and returning any of those would leave the
          -- skeleton's records in the export with the model that needed them
          -- gone. `st` is the state as it stood before this declaration.
          setEnv saved
          -- **Carry the skeleton's own reason.** The descent recorded why it
          -- could not model it, and that entry is about to be discarded with
          -- the rest of the withdrawn state; a message that says only "the
          -- skeleton did not model" names where a value stopped rather than
          -- why, which is the defect class this repository has paid for most.
          let inner := (st2.2.1.declined.find? fun (m, _) => m == n).map (·.2)
          -- **"spliced inductive", not "spliced index erasure".** The carve arm's
          -- skeleton was the only occupant when this was written; the tree arm's
          -- fragment is seventeen more, and none of them is an index
          -- erasure. A reason that misnames what stopped is the defect class
          -- this line already exists to avoid.
          let why := s!"prim model shape: the spliced inductive {n} did not model, so \
            emitting would leave an unmodelled inductive in front of a consumer \
            (the splice-closure rule) — {inner.getD "and the descent recorded no reason"}"
          return (st.1, { st.2.1 with declined := st.2.1.declined.push (tname, why) },
            st.2.2.1, st.2.2.2)
    return st2

/-- One plain mutual block's model, generated and accounted for —
[`InductiveModels.mutualIso`], or under `presentation` the mutual one-layer
adapter where the block qualifies. The adapter presents an input's interface,
and the entry asks for it for input blocks only: a block a nested model
specialised into never had it — the nested route called the construction
directly — and asking for it there costs two and a half times the
declarations and, on `nested_default_iota`, does not yet spell the composed
recursor's ι rule literally. Whether it should extend to composed blocks is a
question about the adapter, left where the old seam left it.

The implementation inductives the model composes into —
`T._model._impl.tag` and `T._model._impl.aux` — are declarations of the output
like any other and go back through the entry: the tag is a plain sum and takes
the simple construction, the auxiliary is indexed and takes the carve arm.
Their own public carriers are the declaration-local names
`T._model._impl.tag._model` and `T._model._impl.aux._model`.

Composition completes in the same disposable environment as the mutual model;
retaining a job after its generated owner
would retain precisely the ownerful state this pass is designed to discard. -/
partial def genMutual (all : Array Name) (lparams : List Name) (np : Nat)
    (tys : Array Expr) (ctors : Array (Array (Name × Expr)))
    (projections : Array EProjection)
    (reserved : Std.HashSet Name) (routing : Routing)
    (st : ModelIslandState α) (sourceBlock? : Option EDecl := none)
    (presentation : Bool := true)
    (exactTransform : EDecl → EDecl := id)
    (observer? : Option (IslandObserver α) := none) : MetaM (ModelIslandState α) := do
  let (out, rep, pending, observations) := st
  let saved ← getEnv
  let generate := fun (buildRoot? : Option Name) => do
    let selected ← match sourceBlock? with
      | some source => if presentation then mutualOneLayerEligible source else pure false
      | none => pure false
    if selected then
      let some source := sourceBlock?
        | badShape "selected mutual one-layer family has no exact source block"
      let is ← mutualOneLayerIso source reserved buildRoot?
      let normalizer := ({ metaLine := .null, decls := #[source] } : Export).exactNormalizationEnv
      addSourceStructureModels source projections normalizer reserved is
    else
      let is ← mutualIso all lparams np tys ctors reserved buildRoot?
        (sourceBlock? := sourceBlock?)
      addInstalledStructureModels all projections reserved is
  let mut result ← (generate none).run
  if let .error (.nameLost _) := result then
    setEnv saved
    result ← (generate (some (Naming.retryRoot all[0]!))).run
  match result with
  | .error dec =>
    setEnv saved
    return (out, rep.withDecline all[0]! dec "mutual",
      pending, observations)
  | .ok is =>
    let source ← match sourceBlock? with
      | some block => pure block
      | none => indEDecl all
    let serialised ← serialiseIso source is exactTransform observer?
    let records := serialised.records
    let is := serialised.model
    let out := appendModelRecords out records all[0]!
    let mut rep := { rep with generated := rep.generated.push (all[0]!, is.decls.size) }
    unless is.spliced.isEmpty do
      rep := { rep with spliced := rep.spliced.push (all[0]!, is.spliced) }
    let observations := serialised.observation?.elim observations observations.push
    let st := (out, rep, pending.push { spliced := is.spliced }, observations)
    modelMembers is.members serialised.exactBlocks .composed routing reserved st
      exactTransform observer?

end

/-- Generation settings used by the aggregate fixture suite: nested and mutual
models remain enabled, while simple models and their bootstrap closure move
together. -/
def legacyGenerationConfig (primModels : Bool) : Cli.Config :=
  { simple := primModels, basic := primModels }
