import InductiveModels.Driver.Serialise

/-!
# Composing the rungs

The three entry points that turn a replayed block into an island:
[`genPrim`] models one member from the primitive basis, [`primCompose`] runs
`genPrim` over the members of a block and composes the results, and
[`genMutual`] takes the mutual route and falls back to composition.

This is where the three constructions meet; nothing above it knows there is
more than one.
-/

open Lean Meta

namespace InductiveModels

private abbrev ModelIslandState (α : Type) :=
  Array EDecl × Report × Array PendingModel × Array α


/-- An exact public name generated by an earlier composed step is not part of
the input's `reserved` set.  Check those spellings before a collision-safe
retry so aliasing can never weaken `nameTaken`. -/
def exactPrimNameTaken? (tname : Name) (ctors : Array (Name × Expr))
    (_projections : Array EProjection) : MetaM (Option Name) := do
  let env ← getEnv
  let recursor := Name.str tname "rec"
  for n in #[Naming.modelName tname, Naming.modelName recursor] do
    if env.constants.contains n then return some n
  for (ctor, _) in ctors do
    let n := Naming.modelName ctor
    if env.constants.contains n then return some n
  for j in [0:ctors.size] do
    let n := Naming.iotaName recursor j
    if env.constants.contains n then return some n
  if let some (.recInfo info) := env.constants.find? recursor then
    if info.k then
      let n := Naming.ruleKName recursor
      if env.constants.contains n then return some n
  if let some (.inductInfo info) := env.constants.find? tname then
    -- The block as export records, so the eta name is predicted by the very
    -- predicate that emits it — including its reading of recursion, which is
    -- what survives reduction and not `info.isRec`.
    let .induct blockTypes blockCtors _ ← indEDecl info.all.toArray | return none
    let some type := blockTypes.find? (·.name == tname) | return none
    if type.isKernelStructureLike blockCtors (.ofEnvironment env) &&
        !(← isPropFormerType info.type) then
      let n := Naming.etaName tname
      if env.constants.contains n then return some n
    if ctors.size == 1 then
      let ctorName := ctors[0]!.1
      let some constructor := blockCtors.find? fun constructor =>
          constructor.name == ctorName && constructor.induct == tname
        | return none
      for fieldIndex in ← eligibleProjectionFieldsM type constructor do
        for n in #[Naming.projectionName tname fieldIndex,
            Naming.projectionIotaName tname fieldIndex] do
          if env.constants.contains n then return some n
  return none

/-- One simple inductive's model from the primitives, generated and
accounted for — [`InductiveModels.primIso`], selected by `--simple`. Shared by the
input's own simple inductives and the composition (the single inductives the
other two constructions emit).

**And, with `basicModels`, models for whatever that model had to splice.**

The second half closes a structural hole rather than adding a convenience.
`ensurePrim` and friends put a spliced inductive into the environment and into
the output, and nothing ever ran the third construction over it — so layer 3
was **unable to model anything it introduced**, and no coverage figure could
show it, because a spliced declaration was never a candidate to begin with.
Earlier coverage figures therefore measured only declarations from the input.

Only *non-basis* splices are modelled: the four on
[`InductiveModels.inductiveBasis`] are the exemption that makes the construction
well-founded and must stay unmodelled. That is also what bounds the recursion
— a model's own splices are basis members or already present.

**Ordering is constructive.** A spliced inductive enters the private forest as
part of its consumer's model. Its model is placed immediately before that exact
owner record while retaining the parent's earlier dependency prefix. -/
partial def genPrim (tname : Name) (lparams : List Name) (np : Nat) (ty : Expr)
    (ctors : Array (Name × Expr))
    (projections : Array EProjection)
    (reserved : Std.HashSet Name) (basicModels : Bool)
    (st : ModelIslandState α) (sourceBlock? : Option (EDecl × ExactNormalizationEnv) := none)
    (exactTransform : EDecl → EDecl := id)
    (observer? : Option (IslandObserver α) := none) :
    MetaM (ModelIslandState α) := do
  let (out, rep, pending, observations) := st
  let saved ← getEnv
  -- **The retry under an alias root**, and it is a retry rather than a
  -- decision taken up front on purpose: aliasing changes nothing about the
  -- output and everything about the risk, so it runs only where the collision
  -- has actually fired. Every declaration that models today takes exactly the
  -- path it took before, byte for byte.
  --
  -- The alias embeds the exact original below a public namespace.  This is
  -- injective even for distinct raw private names that normalize to the same
  -- user name, because `_private` is no longer the leading component.
  let aliasRoot : Name := Naming.retryRoot tname
  let mut root := tname
  let sourceRecursor? := sourceBlock?.bind fun (block, _) => match block with
    | .induct _ _ recursors => recursors.find? (·.name == Name.str tname "rec")
    | _ => none
  let sourceType? := sourceBlock?.bind fun (block, _) => match block with
    | .induct types _ _ => types.find? (·.name == tname)
    | _ => none
  let sourceConstructor? := sourceBlock?.bind fun (block, _) => match block with
    | .induct _ constructors _ => constructors.find? (·.induct == tname)
    | _ => none
  let attachStructureModels := fun (is : Iso) => match sourceBlock? with
    | some (block, normalizer) =>
      addSourceStructureModels block projections normalizer reserved is
    | none => addInstalledStructureModels #[tname] projections reserved is
  -- **Route selection is a property of the declaration, not of its
  -- provenance.** The predicate below reads only the block being modelled —
  -- its exact serialized type, constructor and recursor — so an inductive a
  -- model spliced (arm C's index erasure, the composition's tag and
  -- auxiliary) is asked exactly the question an input inductive is asked.
  -- Gating the question on "did this come from the input stream?" made a
  -- generated owner miss the one-layer implementation certificate that its own
  -- source owner carries, and with it the literal projection-iota contract
  -- ([`InductiveModels.addProjectionModels`]); the erasure skeleton of an
  -- indexed fibre owner was the observable case.
  --
  -- **An unindexed owner has no adapter at all.** It is the simple
  -- construction's own, whatever its constructor count: the public carrier,
  -- constructor, recursor, ι rules and intrinsic projections all come out of
  -- [`InductiveModels.primIso`] at the exact source syntax, so a private
  -- fixpoint with a rolled public layer over it bought nothing a route had to
  -- exist for and cost one `Eq.rec` transport per recursive field.
  let selectIndexedFibre ←
      match sourceType?, sourceConstructor?, sourceRecursor? with
      | some sourceType, some sourceConstructor, some sourceRecursor =>
        phase1IndexedFibreOneLayerEligible tname np ty ctors sourceType
          sourceConstructor sourceRecursor
      | _, _, _ => pure false
  let exactTaken ← exactPrimNameTaken? tname ctors projections
  let initial ← match exactTaken with
    | some n => pure (.error (.nameTaken n))
    | none => (do
        let is ← if selectIndexedFibre then
            let some sourceRecursor := sourceRecursor?
              | badShape s!"{tname}'s selected indexed fibre has no exact recursor"
            let some sourceConstructor := ctors[0]?
              | badShape s!"{tname}'s selected indexed fibre has no constructor"
            indexedFibreOneLayerIso tname root lparams np ty sourceConstructor sourceRecursor reserved
          else
            primIso tname root lparams np ty ctors reserved
              (sourceRecursor? := sourceRecursor?)
        attachStructureModels is).run
  let mut res := initial
  if let .error (.nameLost _) := res then
    setEnv saved
    root := aliasRoot
    res ← (do
      let is ← if selectIndexedFibre then
          let some sourceRecursor := sourceRecursor?
            | badShape s!"{tname}'s selected indexed fibre has no exact recursor"
          let some sourceConstructor := ctors[0]?
            | badShape s!"{tname}'s selected indexed fibre has no constructor"
          indexedFibreOneLayerIso tname root lparams np ty sourceConstructor sourceRecursor reserved
        else
          primIso tname root lparams np ty ctors reserved
            (sourceRecursor? := sourceRecursor?)
      attachStructureModels is).run
  match res with
  | .error dec =>
    setEnv saved
    -- **Exempt is not declined.** A basis primitive is what the construction
    -- is written in, so its absence from the models is the thing that makes
    -- the construction well-founded rather than a shape it cannot reach; it
    -- gets its own row and is out of the decline count.
    if dec matches .basisExempt then
      return (out, { rep with exempt := rep.exempt.push (tname, dec.labelAs "prim") },
        pending, observations)
    return (out, rep.withDecline tname dec "prim",
      pending, observations)
  | .ok is =>
    let source ← match sourceBlock? with
      | some (block, _) => pure block
      | none => indEDecl #[tname]
    let serialised ← serialiseIso source is exactTransform observer?
    let records := serialised.records
    let is := serialised.model
    let out := appendModelRecords out records tname
    let mut rep := { rep with generated := rep.generated.push (tname, is.decls.size) }
    unless is.spliced.isEmpty do
      rep := { rep with spliced := rep.spliced.push (tname, is.spliced) }
    let observations := serialised.observation?.elim observations observations.push
    let mut st2 := (out, rep, pending.push { spliced := is.spliced }, observations)
    if basicModels then
      for n in is.spliced do
        if inductiveBasis.contains n then continue
        let some (.inductInfo iv) := (← getEnv).constants.find? n | continue
        -- the block's own name only, and only a simple one
        unless iv.all == [n] && iv.numNested == 0 do continue
        -- Already modeled: the declaration-local carrier itself is the key.
        if (← getEnv).constants.contains (Naming.modelName n) then continue
        let mut cts : Array (Name × Expr) := #[]
        for cn in iv.ctors do
          if let some ci := (← getEnv).constants.find? cn then cts := cts.push (cn, ci.type)
        let exactBlock ← serialised.exactBlocks.require n
        -- Generated projection-iota closing uses only `ExactNormalizationEnv.beta`;
        -- that operation deliberately consults no named definition, so a
        -- one-block normalizer cannot lose persistent/source aliases.
        let normalizer := ({ metaLine := .null, decls := #[exactBlock] } : Export).exactNormalizationEnv
        st2 ←
          genPrim n iv.levelParams iv.numParams iv.type cts #[] reserved
            basicModels st2 (some (exactBlock, normalizer)) exactTransform
            (observer? := observer?)
    -- **A model may not leave an inductive it introduced unmodelled.** Arm C
    -- splices the index erasure of the family it is
    -- carving, so its output contains an inductive that was in nobody's
    -- input; if the descent above could not model it, emitting would put a
    -- additional unmodelled inductive in front of a consumer, which splice
    -- closure prevents.
    -- So the whole model is withdrawn and the declaration declines.
    --
    -- Checked **after** the descent and not predicted before it. A cheap test
    -- that says "this skeleton will model" is the shape of "skip is not
    -- pass": it reports success and leaves the hole open on the case it got
    -- wrong. This asks the environment.
    if basicModels then
      for n in is.requires do
        unless (← getEnv).constants.contains (Naming.modelName n) do
          -- **Withdraw everything**, and off `st` rather than off the locals:
          -- `out`, `rep` and `pending` have all been added to by the emission
          -- and the descent above, and returning any of those would leave the
          -- skeleton's records in the export with the model that needed them
          -- gone. `st` is the state as it stood before this declaration.
          setEnv saved
          -- **Carry the skeleton's own reason.** The descent recorded why it
          -- could not model it, and that entry is about to be discarded with
          -- the rest of the withdrawn state; a message that says only "the
          -- skeleton did not model" names where a value stopped rather than
          -- why, which is the defect class this repository has paid for most.
          let inner := (st2.2.1.declined.find? fun (m, _) => m == n).map (·.2)
          -- **"spliced inductive", not "spliced index erasure".** Arm C's
          -- skeleton was the only occupant when this was written; arm W's
          -- fragment is seventeen more, and none of them is an index
          -- erasure. A reason that misnames what stopped is the defect class
          -- this line already exists to avoid.
          let why := s!"prim model shape: the spliced inductive {n} did not model, so \
            emitting would leave an unmodelled inductive in front of a consumer \
            (the splice-closure rule) — {inner.getD "and the descent recorded no reason"}"
          return (st.1, { st.2.1 with declined := st.2.1.declined.push (tname, why) },
            st.2.2.1, st.2.2.2)
    return st2

/-- **The composition's third step**: the implementation inductives a mutual
model just emitted — `T._model._impl.tag` and `T._model._impl.aux` — are
declarations of the output like any other, so the simple branch runs on them
too. The tag is a plain sum and models; the auxiliary is indexed and takes
arm C. Their own public carriers are the declaration-local names
`T._model._impl.tag._model` and `T._model._impl.aux._model`.

Composition completes in the same disposable environment as the mutual model;
retaining a job after its generated owner
would retain precisely the ownerful state this pass is designed to discard. -/
def primCompose (members : Array Name) (lparams : List Name) (np : Nat)
    (reserved : Std.HashSet Name) (basicModels : Bool)
    (blocks : ExactGeneratedBlocks) (st : ModelIslandState α)
    (exactTransform : EDecl → EDecl := id)
    (observer? : Option (IslandObserver α) := none) : MetaM (ModelIslandState α) := do
  let mut st := st
  for n in members do
    let some (.inductInfo iv) := (← getEnv).constants.find? n | continue
    let mut cts : Array (Name × Expr) := #[]
    for cn in iv.ctors do
      let some ci := (← getEnv).constants.find? cn | continue
      cts := cts.push (cn, ci.type)
    let exactBlock ← blocks.require n
    let normalizer := ({ metaLine := .null, decls := #[exactBlock] } : Export).exactNormalizationEnv
    st ←
      genPrim n lparams np iv.type cts #[] reserved basicModels st
        (some (exactBlock, normalizer)) exactTransform
        (observer? := observer?)
  return st

/-- One plain mutual block's model, generated and accounted for.

A separate function keeps the block path and the nested composition path on
one implementation. The basic layer controls the support closure of each
generated implementation tag and auxiliary model. -/
def genMutual (all : Array Name) (lparams : List Name) (np : Nat)
    (tys : Array Expr) (ctors : Array (Array (Name × Expr)))
    (projections : Array EProjection)
    (reserved : Std.HashSet Name) (simpleModels basicModels : Bool)
    (st : ModelIslandState α) (sourceBlock? : Option EDecl := none)
    (exactTransform : EDecl → EDecl := id)
    (observer? : Option (IslandObserver α) := none) : MetaM (ModelIslandState α) := do
  let (out, rep, pending, observations) := st
  let saved ← getEnv
  let generate := fun (buildRoot? : Option Name) => do
    let selected ← match sourceBlock? with
      | some source => mutualOneLayerEligible source
      | none => pure false
    if selected then
      let some source := sourceBlock?
        | badShape "selected mutual one-layer family has no exact source block"
      let is ← mutualOneLayerIso source reserved buildRoot?
      let normalizer := ({ metaLine := .null, decls := #[source] } : Export).exactNormalizationEnv
      addSourceStructureModels source projections normalizer reserved is
    else
      let is ← mutualIso all lparams np tys ctors reserved buildRoot?
        (sourceBlock? := sourceBlock?)
      addInstalledStructureModels all projections reserved is
  let mut result ← (generate none).run
  if let .error (.nameLost _) := result then
    setEnv saved
    result ← (generate (some (Naming.retryRoot all[0]!))).run
  match result with
  | .error dec =>
    setEnv saved
    return (out, rep.withDecline all[0]! dec "mutual",
      pending, observations)
  | .ok is =>
    let source ← match sourceBlock? with
      | some block => pure block
      | none => indEDecl all
    let serialised ← serialiseIso source is exactTransform observer?
    let records := serialised.records
    let is := serialised.model
    let out := appendModelRecords out records all[0]!
    let mut rep := { rep with generated := rep.generated.push (all[0]!, is.decls.size) }
    unless is.spliced.isEmpty do
      rep := { rep with spliced := rep.spliced.push (all[0]!, is.spliced) }
    let observations := serialised.observation?.elim observations observations.push
    let st := (out, rep, pending.push { spliced := is.spliced }, observations)
    if simpleModels then
      primCompose is.members is.levelParams np reserved basicModels serialised.exactBlocks st
        exactTransform observer?
    else
      return st

/-- Generation settings used by the aggregate fixture suite: nested and mutual
models remain enabled, while simple models and their bootstrap closure move
together. -/
def legacyGenerationConfig (primModels : Bool) : Cli.Config :=
  { simple := primModels, basic := primModels }
