import InductiveModels.Order

/-!
# Kernel checking of export declarations

The batch input checker consumes `EDecl` values directly and has no dependency
on output formatting, JSON rendering, or physical staging. Generated output is
checked separately at each model-island boundary by `checkGeneratedIn`.
-/

open Lean Meta

namespace InductiveModels

namespace KernelCheck

private def exportedRecursorRules (recursor : ERec) : List RecursorRule :=
  recursor.rules.map fun rule : ERecRule =>
    { ctor := rule.ctor, nfields := rule.nfields, rhs := rule.rhs }

private def metadataMismatch (name : Name) (kind field : String) : String :=
  s!"{name}: {kind} {field} differs from Lean's kernel"

/-- Compare one exported inductive record with the metadata regenerated by the
kernel environment which accepted it. -/
def checkInductiveMetadataIn (env : Environment) (types : List EIndType)
    (constructors : List ECtor) (recursors : List ERec) : Array String := Id.run do
  let mut mismatches : Array String := #[]
  for type in types do
    match env.constants.find? type.name with
    | some (.inductInfo actual) =>
      unless actual.name == type.name do
        mismatches := mismatches.push (metadataMismatch type.name "inductive" "name")
      unless actual.levelParams == type.levelParams do
        mismatches := mismatches.push (metadataMismatch type.name "inductive" "levelParams")
      unless actual.type == type.type do
        mismatches := mismatches.push (metadataMismatch type.name "inductive" "type")
      unless actual.all == type.all do
        mismatches := mismatches.push (metadataMismatch type.name "inductive" "all")
      unless actual.ctors == type.ctors do
        mismatches := mismatches.push (metadataMismatch type.name "inductive" "constructors")
      unless actual.numParams == type.numParams do
        mismatches := mismatches.push (metadataMismatch type.name "inductive" "numParams")
      unless actual.numIndices == type.numIndices do
        mismatches := mismatches.push (metadataMismatch type.name "inductive" "numIndices")
      unless actual.numNested == type.numNested do
        mismatches := mismatches.push (metadataMismatch type.name "inductive" "numNested")
      unless actual.isRec == type.isRec do
        mismatches := mismatches.push (metadataMismatch type.name "inductive" "isRec")
      unless actual.isReflexive == type.isReflexive do
        mismatches := mismatches.push (metadataMismatch type.name "inductive" "isReflexive")
      unless actual.isUnsafe == type.isUnsafe do
        mismatches := mismatches.push (metadataMismatch type.name "inductive" "isUnsafe")
    | some _ => mismatches := mismatches.push (metadataMismatch type.name "declaration" "kind")
    | none => mismatches := mismatches.push (metadataMismatch type.name "inductive" "presence")
  for constructor in constructors do
    match env.constants.find? constructor.name with
    | some (.ctorInfo actual) =>
      unless actual.name == constructor.name do
        mismatches := mismatches.push (metadataMismatch constructor.name "constructor" "name")
      unless actual.levelParams == constructor.levelParams do
        mismatches := mismatches.push
          (metadataMismatch constructor.name "constructor" "levelParams")
      unless actual.type == constructor.type do
        mismatches := mismatches.push (metadataMismatch constructor.name "constructor" "type")
      unless actual.induct == constructor.induct do
        mismatches := mismatches.push (metadataMismatch constructor.name "constructor" "induct")
      unless actual.cidx == constructor.cidx do
        mismatches := mismatches.push (metadataMismatch constructor.name "constructor" "cidx")
      unless actual.numParams == constructor.numParams do
        mismatches := mismatches.push
          (metadataMismatch constructor.name "constructor" "numParams")
      unless actual.numFields == constructor.numFields do
        mismatches := mismatches.push
          (metadataMismatch constructor.name "constructor" "numFields")
      unless actual.isUnsafe == constructor.isUnsafe do
        mismatches := mismatches.push
          (metadataMismatch constructor.name "constructor" "isUnsafe")
    | some _ =>
      mismatches := mismatches.push (metadataMismatch constructor.name "declaration" "kind")
    | none =>
      mismatches := mismatches.push (metadataMismatch constructor.name "constructor" "presence")
  for recursor in recursors do
    match env.constants.find? recursor.name with
    | some (.recInfo actual) =>
      unless actual.name == recursor.name do
        mismatches := mismatches.push (metadataMismatch recursor.name "recursor" "name")
      unless actual.levelParams == recursor.levelParams do
        mismatches := mismatches.push (metadataMismatch recursor.name "recursor" "levelParams")
      unless actual.type == recursor.type do
        mismatches := mismatches.push (metadataMismatch recursor.name "recursor" "type")
      unless actual.all == recursor.all do
        mismatches := mismatches.push (metadataMismatch recursor.name "recursor" "all")
      unless actual.numParams == recursor.numParams do
        mismatches := mismatches.push (metadataMismatch recursor.name "recursor" "numParams")
      unless actual.numIndices == recursor.numIndices do
        mismatches := mismatches.push (metadataMismatch recursor.name "recursor" "numIndices")
      unless actual.numMotives == recursor.numMotives do
        mismatches := mismatches.push (metadataMismatch recursor.name "recursor" "numMotives")
      unless actual.numMinors == recursor.numMinors do
        mismatches := mismatches.push (metadataMismatch recursor.name "recursor" "numMinors")
      unless actual.rules == exportedRecursorRules recursor do
        mismatches := mismatches.push (metadataMismatch recursor.name "recursor" "rules")
      unless actual.k == recursor.k do
        mismatches := mismatches.push (metadataMismatch recursor.name "recursor" "k")
      unless actual.isUnsafe == recursor.isUnsafe do
        mismatches := mismatches.push (metadataMismatch recursor.name "recursor" "isUnsafe")
    | some _ =>
      mismatches := mismatches.push (metadataMismatch recursor.name "declaration" "kind")
    | none =>
      mismatches := mismatches.push (metadataMismatch recursor.name "recursor" "presence")
  return mismatches

private def insertConstantInfo (constants : Std.HashMap Name ConstantInfo)
    (info : ConstantInfo) : Except String (Std.HashMap Name ConstantInfo) := do
  if constants.contains info.name then
    throw s!"duplicate declaration {info.name}"
  return constants.insert info.name info

/-- Reconstruct the exact `ConstantInfo` map represented by an export.  This
preflight preserves duplicate-name and malformed-safety precedence for the
batch API before any declaration reaches the incremental checker. -/
def constantInfos (x : Export) : Except String (Std.HashMap Name ConstantInfo) := do
  let mut constants : Std.HashMap Name ConstantInfo := {}
  for declaration in x.decls do
    match declaration with
    | .ax name levelParams type isUnsafe =>
      constants ← insertConstantInfo constants <| .axiomInfo
        { name, levelParams, type, isUnsafe }
    | .defn name levelParams type value hints safety all =>
      let some safety := safetyOf? safety
        | throw s!"unknown definition safety {safety}"
      constants ← insertConstantInfo constants <| .defnInfo
        { name, levelParams, type, value, hints := hintsTo hints, safety, all }
    | .thm name levelParams type value all =>
      constants ← insertConstantInfo constants <| .thmInfo
        { name, levelParams, type, value, all }
    | .opaq name levelParams type value isUnsafe all =>
      constants ← insertConstantInfo constants <| .opaqueInfo
        { name, levelParams, type, value, isUnsafe, all }
    | .quot name levelParams type kind =>
      let some kind := quotKindOf? kind
        | throw s!"unknown quotient kind {kind}"
      constants ← insertConstantInfo constants <| .quotInfo
        { name, levelParams, type, kind }
    | .induct types constructors recursors =>
      for type in types do
        constants ← insertConstantInfo constants <| .inductInfo
          { name := type.name, levelParams := type.levelParams, type := type.type
            all := type.all, ctors := type.ctors, numParams := type.numParams
            numIndices := type.numIndices, numNested := type.numNested, isRec := type.isRec
            isUnsafe := type.isUnsafe, isReflexive := type.isReflexive }
      for constructor in constructors do
        constants ← insertConstantInfo constants <| .ctorInfo
          { name := constructor.name, levelParams := constructor.levelParams
            type := constructor.type, induct := constructor.induct, cidx := constructor.cidx
            numParams := constructor.numParams, numFields := constructor.numFields
            isUnsafe := constructor.isUnsafe }
      for recursor in recursors do
        constants ← insertConstantInfo constants <| .recInfo
          { name := recursor.name, levelParams := recursor.levelParams, type := recursor.type
            all := recursor.all, numParams := recursor.numParams
            numIndices := recursor.numIndices, numMotives := recursor.numMotives
            numMinors := recursor.numMinors, rules := exportedRecursorRules recursor
            k := recursor.k, isUnsafe := recursor.isUnsafe }
  return constants

/-- Whether Lean Kernel Arena omits an entire export record from replay. -/
def replaySkipped : EDecl → Bool
  | .ax _ _ _ isUnsafe => isUnsafe
  | .defn _ _ _ _ _ safety _ =>
    match safetyOf? safety with
    | some .safe => false
    | _ => true
  | .thm .. => false
  | .opaq _ _ _ _ isUnsafe _ => isUnsafe
  | .quot name .. => name == `Quot.mk || name == `Quot.lift || name == `Quot.ind
  | .induct types constructors recursors =>
    !types.isEmpty && types.all (·.isUnsafe) && constructors.all (·.isUnsafe) &&
      recursors.all (·.isUnsafe)

/-- Exact constants used by the declaration submitted to the kernel. Skipped
unsafe/partial records deliberately have no kernel dependency roots. -/
def inputReferences (declaration : EDecl) : Std.HashSet Name := Id.run do
  if replaySkipped declaration then return {}
  let mut roots : Array Expr := #[]
  match declaration with
  | .ax _ _ type _ => roots := roots.push type
  | .defn _ _ type value _ _ _ => roots := roots.push type |>.push value
  | .thm _ _ type value _ => roots := roots.push type |>.push value
  | .opaq _ _ type value _ _ => roots := roots.push type |>.push value
  | .quot _ _ type _ => roots := roots.push type
  | .induct types constructors _ =>
    for type in types do roots := roots.push type.type
    for constructor in constructors do roots := roots.push constructor.type
  let mut references := Order.expressionReferences roots
  if let .quot .. := declaration then references := references.insert `Eq
  return references

private def findInductiveType (types : List EIndType) (name : Name) : Except String EIndType :=
  match types.find? (·.name == name) with
  | some type => .ok type
  | none => .error s!"inductive block names missing member {name}"

private def findConstructor (constructors : List ECtor) (name : Name) : Except String ECtor :=
  match constructors.find? (·.name == name) with
  | some constructor => .ok constructor
  | none => .error s!"inductive block names missing constructor {name}"

/-- Reconstruct exactly the declaration submitted by the kernel arena. -/
def replayDeclaration (declaration : EDecl) : Except String (Option Declaration) := do
  if replaySkipped declaration then return none
  match declaration with
  | .ax name levelParams type isUnsafe =>
    return some <| .axiomDecl { name, levelParams, type, isUnsafe }
  | .defn name levelParams type value hints safety all =>
    let some safety := safetyOf? safety | throw s!"unknown definition safety {safety}"
    return some <| .defnDecl
      { name, levelParams, type, value, hints := hintsTo hints, safety, all }
  | .thm name levelParams type value all =>
    return some <| .thmDecl { name, levelParams, type, value, all }
  | .opaq name levelParams type value isUnsafe all =>
    return some <| .opaqueDecl { name, levelParams, type, value, isUnsafe, all }
  | .quot .. => return some .quotDecl
  | .induct types constructors _ =>
    let first ← match types with
      | first :: _ => pure first
      | [] => throw "empty inductive declaration"
    let orderedTypes ← first.all.mapM (findInductiveType types)
    let inductiveTypes ← orderedTypes.mapM fun type => do
      let orderedConstructors ← type.ctors.mapM (findConstructor constructors)
      let ctors : List Constructor := orderedConstructors.map fun constructor =>
        { name := constructor.name, type := constructor.type }
      return ({ name := type.name, type := type.type, ctors } : InductiveType)
    return some <| .inductDecl first.levelParams first.numParams inductiveTypes false

/-- Reproduce the former whole-export metadata traversal exactly: ordinary
constants follow the preflight hash-map iteration, then inductive records
follow export order. -/
private def batchMetadataMismatches (constants : Std.HashMap Name ConstantInfo)
    (x : Export) (checked : Environment) : Array String := Id.run do
  let mut mismatches : Array String := #[]
  for (_, expected) in constants do
    if expected.isUnsafe || expected.isPartial then continue
    match expected, checked.constants.find? expected.name with
    | .axiomInfo expected, some (.axiomInfo actual) =>
      unless actual == expected do
        mismatches := mismatches.push (metadataMismatch expected.name "axiom" "metadata")
    | .defnInfo expected, some (.defnInfo actual) =>
      unless actual == expected do
        mismatches := mismatches.push (metadataMismatch expected.name "definition" "metadata")
    | .thmInfo expected, some (.thmInfo actual) =>
      unless actual == expected do
        mismatches := mismatches.push (metadataMismatch expected.name "theorem" "metadata")
    | .opaqueInfo expected, some (.opaqueInfo actual) =>
      unless actual == expected do
        mismatches := mismatches.push
          (metadataMismatch expected.name "opaque declaration" "metadata")
    | .quotInfo _, _ | .inductInfo _, _ | .ctorInfo _, _ | .recInfo _, _ => pure ()
    | _, _ =>
      mismatches := mismatches.push
        (metadataMismatch expected.name "declaration" "kind or presence")
  for declaration in x.decls do
    if let .induct types constructors recursors := declaration then
      unless replaySkipped declaration do
        mismatches := mismatches ++
          checkInductiveMetadataIn checked types constructors recursors
  return mismatches

/-- Peel `n` `∀` binders, keeping them, and return them with what is left. -/
private def peelForalls (n : Nat) (e : Expr) :
    Option (Array (Name × Expr × BinderInfo) × Expr) := Id.run do
  let mut binders : Array (Name × Expr × BinderInfo) := #[]
  let mut cur := e
  for _ in [0:n] do
    let .forallE x dom body info := cur | return none
    binders := binders.push (x, dom, info)
    cur := body
  return some (binders, cur)

/-- **The type a recursor's ι rule asserts for its own right-hand side.**

A `RecursorRule` is not free-standing: the recursor's declared type already
says what `R p⃗ M⃗ m⃗ ι⃗_j (C_j p⃗ x⃗)` reduces at, so the rule's right-hand side
has exactly one admissible type,

    ∀ p⃗ M⃗ m⃗ x⃗, M ι⃗_j (C_j p⃗ x⃗)

read off `R`'s own type and `C_j`'s own type and nothing else.

Built in de Bruijn rather than through a `Meta` telescope: the environment this
runs in is `Environment.ofKernelEnv` of the replay, whose constants
`Environment.find?` — and therefore `inferType` — does not see. `none` where
the record's own arities do not admit the reading above; the metadata
comparison beside this one is what reports those. -/
private def recursorRuleType? (env : Kernel.Environment) (recursor : ERec)
    (rule : ERecRule) : Option Expr := Id.run do
  let some (.ctorInfo constructor) := env.constants.find? rule.ctor | return none
  let levels := (recursor.levelParams.drop
    (recursor.levelParams.length - constructor.levelParams.length)).map Level.param
  let leading := recursor.numParams + recursor.numMotives + recursor.numMinors
  let some (pre, tail) := peelForalls leading recursor.type | return none
  -- The constructor's parameters are the recursor's own, at the index `∀ p⃗ M⃗ m⃗`
  -- gives them; `instantiate1` lifts each reference as it crosses a binder, so
  -- the field binders peeled next carry the right ones without further work.
  let mut atParameters := constructor.type.instantiateLevelParams
    constructor.levelParams levels
  for k in [0:recursor.numParams] do
    let .forallE _ _ body _ := atParameters | return none
    atParameters := body.instantiate1 (.bvar (leading - 1 - k))
  let some (fields, result) := peelForalls rule.nfields atParameters | return none
  let arguments := result.getAppArgs
  unless arguments.size == recursor.numParams + recursor.numIndices do return none
  let parameterRefs := (Array.range recursor.numParams).map fun k =>
    Expr.bvar (leading - 1 - k + rule.nfields)
  let fieldRefs := (Array.range rule.nfields).map fun i => Expr.bvar (rule.nfields - 1 - i)
  let major := mkAppN (.const rule.ctor levels) (parameterRefs ++ fieldRefs)
  let mut motiveAt := tail.liftLooseBVars 0 rule.nfields
  for argument in (arguments.extract recursor.numParams arguments.size).push major do
    let .forallE _ _ body _ := motiveAt | return none
    motiveAt := body.instantiate1 argument
  for (x, dom, info) in fields.reverse do motiveAt := .forallE x dom motiveAt info
  for (x, dom, info) in pre.reverse do motiveAt := .forallE x dom motiveAt info
  return some motiveAt

/-- **Every exported ι rule, at the type its own recursor demands.**

Lean's kernel derives a recursor rather than checking the one an export
carries, so the metadata comparison above relates the export to that
derivation and is silent about whether the derivation is *itself* coherent. It
need not be. `bad/rec-missing-ih` is an export whose minor premise binds an
induction hypothesis its own ι rule then does not apply — the field it is the
hypothesis for reduces to the owner when the minor premise is built and does
not when the rule is, so the two disagree — and Lean's kernel regenerates that
recursor byte for byte. Nothing which compares the export with the derivation
can see it, because there is nothing to see there.

What sees it is the recursor's own type: a right-hand side of type
`M x → M (C x⃗)` cannot be the reduct of a recursor application at `M (C x⃗)`.
So the rule is submitted to the kernel as an ordinary definition at exactly
that type, and the kernel says whether it is one.

This is a kernel question and belongs behind `--type-check-input` with the
replay, not in the structural checker, which never asks for definitional
equality. -/
def ruleTypeMismatches (env : Kernel.Environment) (x : Export) : IO (Array String) := do
  let mut mismatches : Array String := #[]
  for record in x.decls do
    let .induct _ _ recursors := record | continue
    if replaySkipped record then continue
    for recursor in recursors do
      if recursor.isUnsafe then continue
      for rule in recursor.rules do
        -- **A rule of the recursor's own block, and no other.** A *nested*
        -- block's auxiliary recursor states a rule at the container's
        -- constructor — `Lean.Syntax.rec_2` at `List.nil` — whose parameters
        -- are the nesting and not the recursor's, and no record carries the
        -- instantiation to recover them from. Such a rule's type cannot be
        -- reconstructed here and is not this check's business; the metadata
        -- comparison above still relates it to Lean's own derivation.
        let some (.ctorInfo constructor) := env.constants.find? rule.ctor | continue
        unless recursor.all.contains constructor.induct do continue
        let some expected := recursorRuleType? env recursor rule
          | mismatches := mismatches.push s!"{recursor.name}: the ι rule for \
{rule.ctor} does not present the arities its own recursor record declares"
            continue
        -- Discarded either way: this asks the kernel a question about `rhs`
        -- and adds nothing to the environment the export builds.
        match env.addDeclCore 0 0 (.defnDecl
            { name := `_ruleTypeCheck, levelParams := recursor.levelParams
              type := expected, value := rule.rhs, hints := .opaque
              safety := .safe, all := [`_ruleTypeCheck] }) none with
        | .ok _ => pure ()
        | .error exception =>
          mismatches := mismatches.push s!"{recursor.name}: the ι rule for {rule.ctor} \
is not a reduct of {recursor.name} at that constructor: \
{← (exception.toMessageData {}).toString}"
  return mismatches

end KernelCheck

/-- Compatibility name for the exact constant-info preflight. -/
def Export.constantInfos (x : Export) : Except String (Std.HashMap Name ConstantInfo) :=
  KernelCheck.constantInfos x

/-- Check a complete input export **in the order it is written**.

This used to replay in a private depth-first dependency schedule, which meant
`--type-check-input` could not see an emission-order defect at all: it computed
its way around one. An export is a stream, Lean's kernel builds an environment
one declaration at a time, and a record that names a constant no earlier record
declares is not replayable — so that is now what happens to it, at the record
which does it. `test/EmissionOrderCensusTest.lean` measures the same property
directly and reports zero forward references across the committed corpus, in
the inputs as well as in the generated output.

A dependency cycle needs no separate pass either: the record which closes it
mentions a constant the stream has not declared, and the kernel says so. -/
def typeCheckExport (x : Export) : MetaM (Except String Unit) := do
  let base ← getEnv
  let constants ← match x.constantInfos with
    | .error message => return .error message
    | .ok constants => pure constants
  let mut checked := base.toKernelEnv
  for record in x.decls do
    let replay ← match KernelCheck.replayDeclaration record with
      | .error message => return .error message
      | .ok replay => pure replay
    if let some declaration := replay then
      match checked.addDeclCore 0 0 declaration none with
      | .error exception =>
        return .error s!"{record.names}: {← (exception.toMessageData {}).toString}"
      | .ok next => checked := next
  let checkedEnv := Environment.ofKernelEnv checked
  -- Preserve the batch API's historical observable state even when the later
  -- serialized-metadata comparison rejects the export.
  setEnv checkedEnv
  let mismatches := KernelCheck.batchMetadataMismatches constants x checkedEnv
  unless mismatches.isEmpty do
    return .error s!"serialized declaration metadata differs from Lean's kernel:\n  \
      {"\n  ".intercalate mismatches.toList}"
  let ruleMismatches ← KernelCheck.ruleTypeMismatches checked x
  unless ruleMismatches.isEmpty do
    return .error s!"a recursor's ι rule is not the rule its own type asserts:\n  \
      {"\n  ".intercalate ruleMismatches.toList}"
  return .ok ()

end InductiveModels
