import InductiveModels.Order

/-!
# Kernel checking of export declarations

The batch input checker consumes `EDecl` values directly and has no dependency
on output formatting, JSON rendering, or physical staging. Generated output is
checked separately at each model-island boundary by `checkGeneratedIn`.
-/

open Lean Meta

namespace InductiveModels

namespace KernelCheck

private def exportedRecursorRules (recursor : ERec) : List RecursorRule :=
  recursor.rules.map fun rule : ERecRule =>
    { ctor := rule.ctor, nfields := rule.nfields, rhs := rule.rhs }

private def metadataMismatch (name : Name) (kind field : String) : String :=
  s!"{name}: {kind} {field} differs from Lean's kernel"

/-- Compare one exported inductive record with the metadata regenerated by the
kernel environment which accepted it. -/
def checkInductiveMetadataIn (env : Environment) (types : List EIndType)
    (constructors : List ECtor) (recursors : List ERec) : Array String := Id.run do
  let mut mismatches : Array String := #[]
  for type in types do
    match env.constants.find? type.name with
    | some (.inductInfo actual) =>
      unless actual.name == type.name do
        mismatches := mismatches.push (metadataMismatch type.name "inductive" "name")
      unless actual.levelParams == type.levelParams do
        mismatches := mismatches.push (metadataMismatch type.name "inductive" "levelParams")
      unless actual.type == type.type do
        mismatches := mismatches.push (metadataMismatch type.name "inductive" "type")
      unless actual.all == type.all do
        mismatches := mismatches.push (metadataMismatch type.name "inductive" "all")
      unless actual.ctors == type.ctors do
        mismatches := mismatches.push (metadataMismatch type.name "inductive" "constructors")
      unless actual.numParams == type.numParams do
        mismatches := mismatches.push (metadataMismatch type.name "inductive" "numParams")
      unless actual.numIndices == type.numIndices do
        mismatches := mismatches.push (metadataMismatch type.name "inductive" "numIndices")
      unless actual.numNested == type.numNested do
        mismatches := mismatches.push (metadataMismatch type.name "inductive" "numNested")
      unless actual.isRec == type.isRec do
        mismatches := mismatches.push (metadataMismatch type.name "inductive" "isRec")
      unless actual.isReflexive == type.isReflexive do
        mismatches := mismatches.push (metadataMismatch type.name "inductive" "isReflexive")
      unless actual.isUnsafe == type.isUnsafe do
        mismatches := mismatches.push (metadataMismatch type.name "inductive" "isUnsafe")
    | some _ => mismatches := mismatches.push (metadataMismatch type.name "declaration" "kind")
    | none => mismatches := mismatches.push (metadataMismatch type.name "inductive" "presence")
  for constructor in constructors do
    match env.constants.find? constructor.name with
    | some (.ctorInfo actual) =>
      unless actual.name == constructor.name do
        mismatches := mismatches.push (metadataMismatch constructor.name "constructor" "name")
      unless actual.levelParams == constructor.levelParams do
        mismatches := mismatches.push
          (metadataMismatch constructor.name "constructor" "levelParams")
      unless actual.type == constructor.type do
        mismatches := mismatches.push (metadataMismatch constructor.name "constructor" "type")
      unless actual.induct == constructor.induct do
        mismatches := mismatches.push (metadataMismatch constructor.name "constructor" "induct")
      unless actual.cidx == constructor.cidx do
        mismatches := mismatches.push (metadataMismatch constructor.name "constructor" "cidx")
      unless actual.numParams == constructor.numParams do
        mismatches := mismatches.push
          (metadataMismatch constructor.name "constructor" "numParams")
      unless actual.numFields == constructor.numFields do
        mismatches := mismatches.push
          (metadataMismatch constructor.name "constructor" "numFields")
      unless actual.isUnsafe == constructor.isUnsafe do
        mismatches := mismatches.push
          (metadataMismatch constructor.name "constructor" "isUnsafe")
    | some _ =>
      mismatches := mismatches.push (metadataMismatch constructor.name "declaration" "kind")
    | none =>
      mismatches := mismatches.push (metadataMismatch constructor.name "constructor" "presence")
  for recursor in recursors do
    match env.constants.find? recursor.name with
    | some (.recInfo actual) =>
      unless actual.name == recursor.name do
        mismatches := mismatches.push (metadataMismatch recursor.name "recursor" "name")
      unless actual.levelParams == recursor.levelParams do
        mismatches := mismatches.push (metadataMismatch recursor.name "recursor" "levelParams")
      unless actual.type == recursor.type do
        mismatches := mismatches.push (metadataMismatch recursor.name "recursor" "type")
      unless actual.all == recursor.all do
        mismatches := mismatches.push (metadataMismatch recursor.name "recursor" "all")
      unless actual.numParams == recursor.numParams do
        mismatches := mismatches.push (metadataMismatch recursor.name "recursor" "numParams")
      unless actual.numIndices == recursor.numIndices do
        mismatches := mismatches.push (metadataMismatch recursor.name "recursor" "numIndices")
      unless actual.numMotives == recursor.numMotives do
        mismatches := mismatches.push (metadataMismatch recursor.name "recursor" "numMotives")
      unless actual.numMinors == recursor.numMinors do
        mismatches := mismatches.push (metadataMismatch recursor.name "recursor" "numMinors")
      unless actual.rules == exportedRecursorRules recursor do
        mismatches := mismatches.push (metadataMismatch recursor.name "recursor" "rules")
      unless actual.k == recursor.k do
        mismatches := mismatches.push (metadataMismatch recursor.name "recursor" "k")
      unless actual.isUnsafe == recursor.isUnsafe do
        mismatches := mismatches.push (metadataMismatch recursor.name "recursor" "isUnsafe")
    | some _ =>
      mismatches := mismatches.push (metadataMismatch recursor.name "declaration" "kind")
    | none =>
      mismatches := mismatches.push (metadataMismatch recursor.name "recursor" "presence")
  return mismatches

private def insertConstantInfo (constants : Std.HashMap Name ConstantInfo)
    (info : ConstantInfo) : Except String (Std.HashMap Name ConstantInfo) := do
  if constants.contains info.name then
    throw s!"duplicate declaration {info.name}"
  return constants.insert info.name info

/-- Reconstruct the exact `ConstantInfo` map represented by an export.  This
preflight preserves duplicate-name and malformed-safety precedence for the
batch API before any declaration reaches the incremental checker. -/
def constantInfos (x : Export) : Except String (Std.HashMap Name ConstantInfo) := do
  let mut constants : Std.HashMap Name ConstantInfo := {}
  for declaration in x.decls do
    match declaration with
    | .ax name levelParams type isUnsafe =>
      constants ← insertConstantInfo constants <| .axiomInfo
        { name, levelParams, type, isUnsafe }
    | .defn name levelParams type value hints safety all =>
      let some safety := safetyOf? safety
        | throw s!"unknown definition safety {safety}"
      constants ← insertConstantInfo constants <| .defnInfo
        { name, levelParams, type, value, hints := hintsTo hints, safety, all }
    | .thm name levelParams type value all =>
      constants ← insertConstantInfo constants <| .thmInfo
        { name, levelParams, type, value, all }
    | .opaq name levelParams type value isUnsafe all =>
      constants ← insertConstantInfo constants <| .opaqueInfo
        { name, levelParams, type, value, isUnsafe, all }
    | .quot name levelParams type kind =>
      let some kind := quotKindOf? kind
        | throw s!"unknown quotient kind {kind}"
      constants ← insertConstantInfo constants <| .quotInfo
        { name, levelParams, type, kind }
    | .induct types constructors recursors =>
      for type in types do
        constants ← insertConstantInfo constants <| .inductInfo
          { name := type.name, levelParams := type.levelParams, type := type.type
            all := type.all, ctors := type.ctors, numParams := type.numParams
            numIndices := type.numIndices, numNested := type.numNested, isRec := type.isRec
            isUnsafe := type.isUnsafe, isReflexive := type.isReflexive }
      for constructor in constructors do
        constants ← insertConstantInfo constants <| .ctorInfo
          { name := constructor.name, levelParams := constructor.levelParams
            type := constructor.type, induct := constructor.induct, cidx := constructor.cidx
            numParams := constructor.numParams, numFields := constructor.numFields
            isUnsafe := constructor.isUnsafe }
      for recursor in recursors do
        constants ← insertConstantInfo constants <| .recInfo
          { name := recursor.name, levelParams := recursor.levelParams, type := recursor.type
            all := recursor.all, numParams := recursor.numParams
            numIndices := recursor.numIndices, numMotives := recursor.numMotives
            numMinors := recursor.numMinors, rules := exportedRecursorRules recursor
            k := recursor.k, isUnsafe := recursor.isUnsafe }
  return constants

/-- Whether Lean Kernel Arena omits an entire export record from replay. -/
def replaySkipped : EDecl → Bool
  | .ax _ _ _ isUnsafe => isUnsafe
  | .defn _ _ _ _ _ safety _ =>
    match safetyOf? safety with
    | some .safe => false
    | _ => true
  | .thm .. => false
  | .opaq _ _ _ _ isUnsafe _ => isUnsafe
  | .quot name .. => name == `Quot.mk || name == `Quot.lift || name == `Quot.ind
  | .induct types constructors recursors =>
    !types.isEmpty && types.all (·.isUnsafe) && constructors.all (·.isUnsafe) &&
      recursors.all (·.isUnsafe)

/-- Exact constants used by the declaration submitted to the kernel. Skipped
unsafe/partial records deliberately have no kernel dependency roots. -/
def inputReferences (declaration : EDecl) : Std.HashSet Name := Id.run do
  if replaySkipped declaration then return {}
  let mut roots : Array Expr := #[]
  match declaration with
  | .ax _ _ type _ => roots := roots.push type
  | .defn _ _ type value _ _ _ => roots := roots.push type |>.push value
  | .thm _ _ type value _ => roots := roots.push type |>.push value
  | .opaq _ _ type value _ _ => roots := roots.push type |>.push value
  | .quot _ _ type _ => roots := roots.push type
  | .induct types constructors _ =>
    for type in types do roots := roots.push type.type
    for constructor in constructors do roots := roots.push constructor.type
  let mut references := Order.expressionReferences roots
  if let .quot .. := declaration then references := references.insert `Eq
  return references

namespace ConstantUniverseArities

/- The same pointer-visited traversal as `Order.ExprReferences`, recording how
   many universe levels each constant occurrence carries instead of the bare
   name. Occurrence order is the traversal order, so the first mismatch a
   declaration contains is reported deterministically. -/
unsafe structure State where
  visited : PtrSet Expr := mkPtrSet
  occurrences : Array (Name × Nat) := #[]

unsafe abbrev M := StateM State

unsafe def visit (e : Expr) : M Unit := do
  if (← get).visited.contains e then return
  modify fun state => { state with visited := state.visited.insert e }
  match e with
  | .const name levels =>
    modify fun state =>
      { state with occurrences := state.occurrences.push (name, levels.length) }
  | .proj _ _ struct => visit struct
  | .app fn arg => visit fn; visit arg
  | .lam _ type body _ | .forallE _ type body _ => visit type; visit body
  | .letE _ type value body _ => visit type; visit value; visit body
  | .mdata _ body => visit body
  | .bvar _ | .fvar _ | .mvar _ | .sort _ | .lit _ => pure ()

unsafe def collectUnsafe (roots : Array Expr) : Array (Name × Nat) :=
  ((roots.forM visit).run {}).2.occurrences

end ConstantUniverseArities

/-- Every constant occurrence in `roots`, with the number of universe levels it
supplies. -/
@[implemented_by ConstantUniverseArities.collectUnsafe]
opaque constantUniverseArities (roots : Array Expr) : Array (Name × Nat) := #[]

/-- Exactly the expressions a reconstructed declaration hands to the kernel. -/
private def declarationExpressions : Declaration → Array Expr
  | .axiomDecl value => #[value.type]
  | .defnDecl value | .thmDecl value => #[value.type, value.value]
  | .opaqueDecl value => #[value.type, value.value]
  | .quotDecl => #[]
  | .mutualDefnDecl values => values.toArray.flatMap fun value => #[value.type, value.value]
  | .inductDecl _ _ types _ =>
    types.toArray.flatMap fun type =>
      #[type.type] ++ type.ctors.toArray.map (·.type)

/-- The universe arities a declaration introduces itself. An inductive record
is the only declaration whose own expressions may name it, and every member of
a block shares the block's level parameters. -/
private def introducedUniverseArities : Declaration → Array (Name × Nat)
  | .axiomDecl value => #[(value.name, value.levelParams.length)]
  | .defnDecl value | .thmDecl value => #[(value.name, value.levelParams.length)]
  | .opaqueDecl value => #[(value.name, value.levelParams.length)]
  | .quotDecl => #[]
  | .mutualDefnDecl values =>
    values.toArray.map fun value => (value.name, value.levelParams.length)
  | .inductDecl levelParams _ types _ =>
    types.toArray.flatMap fun type =>
      #[(type.name, levelParams.length)] ++
        type.ctors.toArray.map fun constructor => (constructor.name, levelParams.length)

/-- Reject a declaration that names a constant with the wrong number of
universe levels, before it is submitted to Lean's kernel.

Lean's kernel requires every `Expr.const` to carry exactly one level per level
parameter of the declaration it names, and `infer_constant` rejects a mismatch
wherever it infers the occurrence's type. An occurrence that reaches reduction
instead of inference is not covered: `test/fixtures/rejected/const_universe_arity.ndjson`
puts one in a `let` value that only `whnf` ever looks at, and Lean 4.29.1
dereferences a null expression in `type_checker::whnf_core`, so the process
dies of SIGSEGV rather than reporting anything. The arity is a kernel
precondition, so it is established here rather than discovered there. -/
def universeArityMismatch? (env : Kernel.Environment) (declaration : Declaration) :
    Option String := Id.run do
  let mut introduced : Std.HashMap Name Nat := {}
  for (name, arity) in introducedUniverseArities declaration do
    introduced := introduced.insert name arity
  for (name, supplied) in constantUniverseArities (declarationExpressions declaration) do
    let expected? := match introduced[name]? with
      | some arity => some arity
      | none => (env.find? name).map (·.levelParams.length)
    if let some expected := expected? then
      unless supplied == expected do
        return some s!"{name} is used with {supplied} universe levels but is \
          declared with {expected}"
  return none

private abbrev ReplayMarks := Array UInt8

private partial def visitRecord (x : Export) (ownership : Std.HashMap Name Nat)
    (index : Nat) (marks : ReplayMarks) (order : Array Nat) :
    Except String (ReplayMarks × Array Nat) := do
  match marks[index]! with
  | 2 => return (marks, order)
  | 1 => throw s!"cyclic kernel declaration dependencies at record {index}: {x.decls[index]!.names}"
  | _ => pure ()
  let mut marks := marks.set! index 1
  let mut order := order
  for name in inputReferences x.decls[index]! do
    if let some dependency := ownership[name]? then
      if dependency != index then
        (marks, order) ← visitRecord x ownership dependency marks order
  marks := marks.set! index 2
  return (marks, order.push index)

/-- Stable input-independent dependency schedule for batch kernel replay. -/
def replayOrder (x : Export) : Except String (Array Nat) := do
  let mut ownership : Std.HashMap Name Nat := {}
  for index in [:x.decls.size] do
    for name in x.decls[index]!.names do
      if let some first := ownership[name]? then
        throw s!"duplicate declaration {name} in records {first} and {index}"
      ownership := ownership.insert name index
  let mut marks : ReplayMarks := Array.replicate x.decls.size 0
  let mut order : Array Nat := #[]
  for index in [:x.decls.size] do
    (marks, order) ← visitRecord x ownership index marks order
  return order

private def findInductiveType (types : List EIndType) (name : Name) : Except String EIndType :=
  match types.find? (·.name == name) with
  | some type => .ok type
  | none => .error s!"inductive block names missing member {name}"

private def findConstructor (constructors : List ECtor) (name : Name) : Except String ECtor :=
  match constructors.find? (·.name == name) with
  | some constructor => .ok constructor
  | none => .error s!"inductive block names missing constructor {name}"

/-- Reconstruct exactly the declaration submitted by the kernel arena. -/
def replayDeclaration (declaration : EDecl) : Except String (Option Declaration) := do
  if replaySkipped declaration then return none
  match declaration with
  | .ax name levelParams type isUnsafe =>
    return some <| .axiomDecl { name, levelParams, type, isUnsafe }
  | .defn name levelParams type value hints safety all =>
    let some safety := safetyOf? safety | throw s!"unknown definition safety {safety}"
    return some <| .defnDecl
      { name, levelParams, type, value, hints := hintsTo hints, safety, all }
  | .thm name levelParams type value all =>
    return some <| .thmDecl { name, levelParams, type, value, all }
  | .opaq name levelParams type value isUnsafe all =>
    return some <| .opaqueDecl { name, levelParams, type, value, isUnsafe, all }
  | .quot .. => return some .quotDecl
  | .induct types constructors _ =>
    let first ← match types with
      | first :: _ => pure first
      | [] => throw "empty inductive declaration"
    let orderedTypes ← first.all.mapM (findInductiveType types)
    let inductiveTypes ← orderedTypes.mapM fun type => do
      let orderedConstructors ← type.ctors.mapM (findConstructor constructors)
      let ctors : List Constructor := orderedConstructors.map fun constructor =>
        { name := constructor.name, type := constructor.type }
      return ({ name := type.name, type := type.type, ctors } : InductiveType)
    return some <| .inductDecl first.levelParams first.numParams inductiveTypes false

/-- Reproduce the former whole-export metadata traversal exactly: ordinary
constants follow the preflight hash-map iteration, then inductive records
follow export order. -/
private def batchMetadataMismatches (constants : Std.HashMap Name ConstantInfo)
    (x : Export) (checked : Environment) : Array String := Id.run do
  let mut mismatches : Array String := #[]
  for (_, expected) in constants do
    if expected.isUnsafe || expected.isPartial then continue
    match expected, checked.constants.find? expected.name with
    | .axiomInfo expected, some (.axiomInfo actual) =>
      unless actual == expected do
        mismatches := mismatches.push (metadataMismatch expected.name "axiom" "metadata")
    | .defnInfo expected, some (.defnInfo actual) =>
      unless actual == expected do
        mismatches := mismatches.push (metadataMismatch expected.name "definition" "metadata")
    | .thmInfo expected, some (.thmInfo actual) =>
      unless actual == expected do
        mismatches := mismatches.push (metadataMismatch expected.name "theorem" "metadata")
    | .opaqueInfo expected, some (.opaqueInfo actual) =>
      unless actual == expected do
        mismatches := mismatches.push
          (metadataMismatch expected.name "opaque declaration" "metadata")
    | .quotInfo _, _ | .inductInfo _, _ | .ctorInfo _, _ | .recInfo _, _ => pure ()
    | _, _ =>
      mismatches := mismatches.push
        (metadataMismatch expected.name "declaration" "kind or presence")
  for declaration in x.decls do
    if let .induct types constructors recursors := declaration then
      unless replaySkipped declaration do
        mismatches := mismatches ++
          checkInductiveMetadataIn checked types constructors recursors
  return mismatches

end KernelCheck

/-- Compatibility name for the exact constant-info preflight. -/
def Export.constantInfos (x : Export) : Except String (Std.HashMap Name ConstantInfo) :=
  KernelCheck.constantInfos x

/-- Check a complete input export in its private dependency schedule. -/
def typeCheckExport (x : Export) : MetaM (Except String Unit) := do
  let base ← getEnv
  let constants ← match x.constantInfos with
    | .error message => return .error message
    | .ok constants => pure constants
  let order ← match KernelCheck.replayOrder x with
    | .error message => return .error message
    | .ok order => pure order
  let mut checked := base.toKernelEnv
  for index in order do
    let record := x.decls[index]!
    let replay ← match KernelCheck.replayDeclaration record with
      | .error message => return .error message
      | .ok replay => pure replay
    if let some declaration := replay then
      if let some message := KernelCheck.universeArityMismatch? checked declaration then
        return .error s!"{record.names}: {message}"
      match checked.addDeclCore 0 0 declaration none with
      | .error exception =>
        return .error s!"{record.names}: {← (exception.toMessageData {}).toString}"
      | .ok next => checked := next
  let checkedEnv := Environment.ofKernelEnv checked
  -- Preserve the batch API's historical observable state even when the later
  -- serialized-metadata comparison rejects the export.
  setEnv checkedEnv
  let mismatches := KernelCheck.batchMetadataMismatches constants x checkedEnv
  unless mismatches.isEmpty do
    return .error s!"serialized declaration metadata differs from Lean's kernel:\n  \
      {"\n  ".intercalate mismatches.toList}"
  return .ok ()

end InductiveModels
