import InductiveModels.Order

/-!
# Incremental kernel checking of export declarations

This module is the value-level boundary for whole-export kernel checking.  It
consumes `EDecl` values directly; it has no dependency on output formatting,
JSON rendering, or physical staging.

`State` accepts declarations in any kernel-valid order.  The batch wrapper at
the end retains the historical input-independent dependency schedule, while a
streaming caller may supply a schedule whose dependencies are already known to
be available.  Kernel insertion failures take precedence over accumulated
metadata mismatches, matching the former whole-export implementation.
-/

open Lean Meta

namespace InductiveModels

namespace KernelCheck

private def exportedRecursorRules (recursor : ERec) : List RecursorRule :=
  recursor.rules.map fun rule : ERecRule =>
    { ctor := rule.ctor, nfields := rule.nfields, rhs := rule.rhs }

private def metadataMismatch (name : Name) (kind field : String) : String :=
  s!"{name}: {kind} {field} differs from Lean's kernel"

/-- Compare one exported inductive record with the metadata regenerated by the
kernel environment which accepted it.  This takes the environment explicitly,
so incremental checking never has to replace a caller's construction `MetaM`
environment merely to inspect the exact replay view. -/
def checkInductiveMetadataIn (env : Environment) (types : List EIndType)
    (constructors : List ECtor) (recursors : List ERec) : Array String := Id.run do
  let mut mismatches : Array String := #[]
  for type in types do
    match env.constants.find? type.name with
    | some (.inductInfo actual) =>
      unless actual.name == type.name do
        mismatches := mismatches.push (metadataMismatch type.name "inductive" "name")
      unless actual.levelParams == type.levelParams do
        mismatches := mismatches.push (metadataMismatch type.name "inductive" "levelParams")
      unless actual.type == type.type do
        mismatches := mismatches.push (metadataMismatch type.name "inductive" "type")
      unless actual.all == type.all do
        mismatches := mismatches.push (metadataMismatch type.name "inductive" "all")
      unless actual.ctors == type.ctors do
        mismatches := mismatches.push (metadataMismatch type.name "inductive" "constructors")
      unless actual.numParams == type.numParams do
        mismatches := mismatches.push (metadataMismatch type.name "inductive" "numParams")
      unless actual.numIndices == type.numIndices do
        mismatches := mismatches.push (metadataMismatch type.name "inductive" "numIndices")
      unless actual.numNested == type.numNested do
        mismatches := mismatches.push (metadataMismatch type.name "inductive" "numNested")
      unless actual.isRec == type.isRec do
        mismatches := mismatches.push (metadataMismatch type.name "inductive" "isRec")
      unless actual.isReflexive == type.isReflexive do
        mismatches := mismatches.push (metadataMismatch type.name "inductive" "isReflexive")
      unless actual.isUnsafe == type.isUnsafe do
        mismatches := mismatches.push (metadataMismatch type.name "inductive" "isUnsafe")
    | some _ => mismatches := mismatches.push (metadataMismatch type.name "declaration" "kind")
    | none => mismatches := mismatches.push (metadataMismatch type.name "inductive" "presence")
  for constructor in constructors do
    match env.constants.find? constructor.name with
    | some (.ctorInfo actual) =>
      unless actual.name == constructor.name do
        mismatches := mismatches.push (metadataMismatch constructor.name "constructor" "name")
      unless actual.levelParams == constructor.levelParams do
        mismatches := mismatches.push
          (metadataMismatch constructor.name "constructor" "levelParams")
      unless actual.type == constructor.type do
        mismatches := mismatches.push (metadataMismatch constructor.name "constructor" "type")
      unless actual.induct == constructor.induct do
        mismatches := mismatches.push (metadataMismatch constructor.name "constructor" "induct")
      unless actual.cidx == constructor.cidx do
        mismatches := mismatches.push (metadataMismatch constructor.name "constructor" "cidx")
      unless actual.numParams == constructor.numParams do
        mismatches := mismatches.push
          (metadataMismatch constructor.name "constructor" "numParams")
      unless actual.numFields == constructor.numFields do
        mismatches := mismatches.push
          (metadataMismatch constructor.name "constructor" "numFields")
      unless actual.isUnsafe == constructor.isUnsafe do
        mismatches := mismatches.push
          (metadataMismatch constructor.name "constructor" "isUnsafe")
    | some _ =>
      mismatches := mismatches.push (metadataMismatch constructor.name "declaration" "kind")
    | none =>
      mismatches := mismatches.push (metadataMismatch constructor.name "constructor" "presence")
  for recursor in recursors do
    match env.constants.find? recursor.name with
    | some (.recInfo actual) =>
      unless actual.name == recursor.name do
        mismatches := mismatches.push (metadataMismatch recursor.name "recursor" "name")
      unless actual.levelParams == recursor.levelParams do
        mismatches := mismatches.push (metadataMismatch recursor.name "recursor" "levelParams")
      unless actual.type == recursor.type do
        mismatches := mismatches.push (metadataMismatch recursor.name "recursor" "type")
      unless actual.all == recursor.all do
        mismatches := mismatches.push (metadataMismatch recursor.name "recursor" "all")
      unless actual.numParams == recursor.numParams do
        mismatches := mismatches.push (metadataMismatch recursor.name "recursor" "numParams")
      unless actual.numIndices == recursor.numIndices do
        mismatches := mismatches.push (metadataMismatch recursor.name "recursor" "numIndices")
      unless actual.numMotives == recursor.numMotives do
        mismatches := mismatches.push (metadataMismatch recursor.name "recursor" "numMotives")
      unless actual.numMinors == recursor.numMinors do
        mismatches := mismatches.push (metadataMismatch recursor.name "recursor" "numMinors")
      unless actual.rules == exportedRecursorRules recursor do
        mismatches := mismatches.push (metadataMismatch recursor.name "recursor" "rules")
      unless actual.k == recursor.k do
        mismatches := mismatches.push (metadataMismatch recursor.name "recursor" "k")
      unless actual.isUnsafe == recursor.isUnsafe do
        mismatches := mismatches.push (metadataMismatch recursor.name "recursor" "isUnsafe")
    | some _ =>
      mismatches := mismatches.push (metadataMismatch recursor.name "declaration" "kind")
    | none =>
      mismatches := mismatches.push (metadataMismatch recursor.name "recursor" "presence")
  return mismatches

private def insertConstantInfo (constants : Std.HashMap Name ConstantInfo)
    (info : ConstantInfo) : Except String (Std.HashMap Name ConstantInfo) := do
  if constants.contains info.name then
    throw s!"duplicate declaration {info.name}"
  return constants.insert info.name info

/-- Reconstruct the exact `ConstantInfo` map represented by an export.  This
preflight preserves duplicate-name and malformed-safety precedence for the
batch API before any declaration reaches the incremental checker. -/
def constantInfos (x : Export) : Except String (Std.HashMap Name ConstantInfo) := do
  let mut constants : Std.HashMap Name ConstantInfo := {}
  for declaration in x.decls do
    match declaration with
    | .ax name levelParams type isUnsafe =>
      constants ← insertConstantInfo constants <| .axiomInfo
        { name, levelParams, type, isUnsafe }
    | .defn name levelParams type value hints safety all =>
      let some safety := safetyOf? safety
        | throw s!"unknown definition safety {safety}"
      constants ← insertConstantInfo constants <| .defnInfo
        { name, levelParams, type, value, hints := hintsTo hints, safety, all }
    | .thm name levelParams type value all =>
      constants ← insertConstantInfo constants <| .thmInfo
        { name, levelParams, type, value, all }
    | .opaq name levelParams type value isUnsafe all =>
      constants ← insertConstantInfo constants <| .opaqueInfo
        { name, levelParams, type, value, isUnsafe, all }
    | .quot name levelParams type kind =>
      let some kind := quotKindOf? kind
        | throw s!"unknown quotient kind {kind}"
      constants ← insertConstantInfo constants <| .quotInfo
        { name, levelParams, type, kind }
    | .induct types constructors recursors =>
      for type in types do
        constants ← insertConstantInfo constants <| .inductInfo
          { name := type.name, levelParams := type.levelParams, type := type.type
            all := type.all, ctors := type.ctors, numParams := type.numParams
            numIndices := type.numIndices, numNested := type.numNested, isRec := type.isRec
            isUnsafe := type.isUnsafe, isReflexive := type.isReflexive }
      for constructor in constructors do
        constants ← insertConstantInfo constants <| .ctorInfo
          { name := constructor.name, levelParams := constructor.levelParams
            type := constructor.type, induct := constructor.induct, cidx := constructor.cidx
            numParams := constructor.numParams, numFields := constructor.numFields
            isUnsafe := constructor.isUnsafe }
      for recursor in recursors do
        constants ← insertConstantInfo constants <| .recInfo
          { name := recursor.name, levelParams := recursor.levelParams, type := recursor.type
            all := recursor.all, numParams := recursor.numParams
            numIndices := recursor.numIndices, numMotives := recursor.numMotives
            numMinors := recursor.numMinors, rules := exportedRecursorRules recursor
            k := recursor.k, isUnsafe := recursor.isUnsafe }
  return constants

/-- Whether Lean Kernel Arena omits an entire export record from replay. -/
def replaySkipped : EDecl → Bool
  | .ax _ _ _ isUnsafe => isUnsafe
  | .defn _ _ _ _ _ safety _ =>
    match safetyOf? safety with
    | some .safe => false
    | _ => true
  | .thm .. => false
  | .opaq _ _ _ _ isUnsafe _ => isUnsafe
  | .quot name .. => name == `Quot.mk || name == `Quot.lift || name == `Quot.ind
  | .induct types constructors recursors =>
    !types.isEmpty && types.all (·.isUnsafe) && constructors.all (·.isUnsafe) &&
      recursors.all (·.isUnsafe)

/-- Constants used by the actual declaration submitted to the kernel. -/
private def inputReferences (declaration : EDecl) : Std.HashSet Name := Id.run do
  if replaySkipped declaration then return {}
  let mut roots : Array Expr := #[]
  match declaration with
  | .ax _ _ type _ => roots := roots.push type
  | .defn _ _ type value _ _ _ => roots := roots.push type |>.push value
  | .thm _ _ type value _ => roots := roots.push type |>.push value
  | .opaq _ _ type value _ _ => roots := roots.push type |>.push value
  | .quot _ _ type _ => roots := roots.push type
  | .induct types constructors _ =>
    for type in types do roots := roots.push type.type
    for constructor in constructors do roots := roots.push constructor.type
  let mut references := Order.expressionReferences roots
  if let .quot .. := declaration then references := references.insert `Eq
  return references

private abbrev ReplayMarks := Array UInt8

private partial def visitRecord (x : Export) (ownership : Std.HashMap Name Nat)
    (index : Nat) (marks : ReplayMarks) (order : Array Nat) :
    Except String (ReplayMarks × Array Nat) := do
  match marks[index]! with
  | 2 => return (marks, order)
  | 1 => throw s!"cyclic kernel declaration dependencies at record {index}: {x.decls[index]!.names}"
  | _ => pure ()
  let mut marks := marks.set! index 1
  let mut order := order
  for name in inputReferences x.decls[index]! do
    if let some dependency := ownership[name]? then
      if dependency != index then
        (marks, order) ← visitRecord x ownership dependency marks order
  marks := marks.set! index 2
  return (marks, order.push index)

/-- Stable input-independent dependency schedule for batch kernel replay. -/
def replayOrder (x : Export) : Except String (Array Nat) := do
  let mut ownership : Std.HashMap Name Nat := {}
  for index in [:x.decls.size] do
    for name in x.decls[index]!.names do
      if let some first := ownership[name]? then
        throw s!"duplicate declaration {name} in records {first} and {index}"
      ownership := ownership.insert name index
  let mut marks : ReplayMarks := Array.replicate x.decls.size 0
  let mut order : Array Nat := #[]
  for index in [:x.decls.size] do
    (marks, order) ← visitRecord x ownership index marks order
  return order

private def findInductiveType (types : List EIndType) (name : Name) : Except String EIndType :=
  match types.find? (·.name == name) with
  | some type => .ok type
  | none => .error s!"inductive block names missing member {name}"

private def findConstructor (constructors : List ECtor) (name : Name) : Except String ECtor :=
  match constructors.find? (·.name == name) with
  | some constructor => .ok constructor
  | none => .error s!"inductive block names missing constructor {name}"

/-- Reconstruct exactly the declaration submitted by the kernel arena. -/
def replayDeclaration (declaration : EDecl) : Except String (Option Declaration) := do
  if replaySkipped declaration then return none
  match declaration with
  | .ax name levelParams type isUnsafe =>
    return some <| .axiomDecl { name, levelParams, type, isUnsafe }
  | .defn name levelParams type value hints safety all =>
    let some safety := safetyOf? safety | throw s!"unknown definition safety {safety}"
    return some <| .defnDecl
      { name, levelParams, type, value, hints := hintsTo hints, safety, all }
  | .thm name levelParams type value all =>
    return some <| .thmDecl { name, levelParams, type, value, all }
  | .opaq name levelParams type value isUnsafe all =>
    return some <| .opaqueDecl { name, levelParams, type, value, isUnsafe, all }
  | .quot .. => return some .quotDecl
  | .induct types constructors _ =>
    let first ← match types with
      | first :: _ => pure first
      | [] => throw "empty inductive declaration"
    let orderedTypes ← first.all.mapM (findInductiveType types)
    let inductiveTypes ← orderedTypes.mapM fun type => do
      let orderedConstructors ← type.ctors.mapM (findConstructor constructors)
      let ctors : List Constructor := orderedConstructors.map fun constructor =>
        { name := constructor.name, type := constructor.type }
      return ({ name := type.name, type := type.type, ctors } : InductiveType)
    return some <| .inductDecl first.levelParams first.numParams inductiveTypes false

private def ordinaryMetadataMismatches (env : Environment) : EDecl → Array String
  | .ax name levelParams type false =>
    match env.constants.find? name with
    | some (.axiomInfo actual) =>
      if actual == { name, levelParams, type, isUnsafe := false } then #[]
      else #[metadataMismatch name "axiom" "metadata"]
    | _ => #[metadataMismatch name "declaration" "kind or presence"]
  | .defn name levelParams type value hints "safe" all =>
    match env.constants.find? name with
    | some (.defnInfo actual) =>
      let expected : DefinitionVal :=
        { name, levelParams, type, value, hints := hintsTo hints, safety := .safe, all }
      if actual == expected then #[] else #[metadataMismatch name "definition" "metadata"]
    | _ => #[metadataMismatch name "declaration" "kind or presence"]
  | .thm name levelParams type value all =>
    match env.constants.find? name with
    | some (.thmInfo actual) =>
      let expected : TheoremVal := { name, levelParams, type, value, all }
      if actual == expected then #[] else #[metadataMismatch name "theorem" "metadata"]
    | _ => #[metadataMismatch name "declaration" "kind or presence"]
  | .opaq name levelParams type value false all =>
    match env.constants.find? name with
    | some (.opaqueInfo actual) =>
      let expected : OpaqueVal := { name, levelParams, type, value, isUnsafe := false, all }
      if actual == expected then #[] else #[metadataMismatch name "opaque declaration" "metadata"]
    | _ => #[metadataMismatch name "declaration" "kind or presence"]
  | .induct types constructors recursors =>
    checkInductiveMetadataIn env types constructors recursors
  | _ => #[]

/-- Incremental exact-value kernel checker.  The latest kernel environment is
the only payload-bearing state retained between pushes.  Once insertion fails,
the unusable environment is released, but later pushes are still counted so a
streaming caller can bind the verdict to its compact schedule. -/
structure State where
  private checked : Option Kernel.Environment
  private replayFailure : Option String := none
  private metadataMismatches : Array String := #[]
  recordsPushed : Nat := 0

def State.create (base : Environment) : State :=
  { checked := some base.toKernelEnv }

def State.push (state : State) (record : EDecl) : MetaM State := do
  let recordsPushed := state.recordsPushed + 1
  let some checked := state.checked
    | return { state with recordsPushed }
  match replayDeclaration record with
  | .error message =>
    let state := { state with checked := none }
    let state := { state with replayFailure := some message }
    return { state with recordsPushed }
  | .ok none => return { state with recordsPushed }
  | .ok (some declaration) =>
    match checked.addDeclCore 0 declaration none with
    | .error exception =>
      let message := s!"{record.names}: {← (exception.toMessageData {}).toString}"
      let state := { state with checked := none }
      let state := { state with replayFailure := some message }
      return { state with recordsPushed }
    | .ok next =>
      let replayEnv := Environment.ofKernelEnv next
      let state := { state with checked := some next }
      let state := { state with replayFailure := none }
      let state := { state with metadataMismatches := state.metadataMismatches ++
        ordinaryMetadataMismatches replayEnv record }
      return { state with recordsPushed }

def State.pushAll (state : State) (records : Array EDecl) : MetaM State := do
  let mut state := state
  for record in records do state ← state.push record
  return state

def State.finish (state : State) : Except String Unit := do
  if let some message := state.replayFailure then throw message
  unless state.metadataMismatches.isEmpty do
    throw s!"serialized declaration metadata differs from Lean's kernel:\n  \
      {"\n  ".intercalate state.metadataMismatches.toList}"
  return ()

end KernelCheck

/-- Compatibility name for the exact constant-info preflight. -/
def Export.constantInfos (x : Export) : Except String (Std.HashMap Name ConstantInfo) :=
  KernelCheck.constantInfos x

/-- Submit a complete export through the same incremental state used by future
declaration-wise callers.  The batch API preserves its historical preflight
and private dependency schedule. -/
def typeCheckExport (x : Export) : MetaM (Except String Unit) := do
  let base ← getEnv
  if let .error message := x.constantInfos then return .error message
  let order ← match KernelCheck.replayOrder x with
    | .error message => return .error message
    | .ok order => pure order
  let mut state := KernelCheck.State.create base
  for index in order do state ← state.push x.decls[index]!
  return state.finish

end InductiveModels
